Repository knative-extensions/eventing-kafka, pull requests merged in 2020-11, with the labels that each got.

#155 We deprecated and never used that anyways in v1beta1
  pkg/apis/bindings/v1alpha1/kafka_conversion_test.go
  pkg/apis/sources/v1alpha1/kafka_conversion_test.go
  pkg/apis/sources/v1beta1/kafka_types.go
  pkg/apis/sources/v1beta1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/M

#158 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_message_handler.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#160 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#159 Sarama logging via configmap
  cmd/channel/distributed/controller/main.go
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  config/channel/distributed/200-eventing-kafka-configmap.yaml
  pkg/channel/distributed/common/config/configwatcher.go
  pkg/channel/distributed/common/kafka/sarama/sarama.go
  pkg/channel/distributed/common/kafka/sarama/sarama_test.go
  pkg/channel/distributed/controller/kafkachannel/controller.go
  pkg/channel/distributed/controller/kafkachannel/reconciler.go
  pkg/channel/distributed/controller/testing/data.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
  pkg/channel/distributed/receiver/producer/producer.go
  pkg/channel/distributed/receiver/producer/producer_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#162 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/L

#161 Refactor Distributed KafkaChannel Cross-Namespace OwnerReferences
  pkg/channel/distributed/controller/constants/constants.go
  pkg/channel/distributed/controller/event/event.go
  pkg/channel/distributed/controller/event/event_test.go
  pkg/channel/distributed/controller/kafkachannel/channel.go
  pkg/channel/distributed/controller/kafkachannel/controller.go
  pkg/channel/distributed/controller/kafkachannel/controller_test.go
  pkg/channel/distributed/controller/kafkachannel/dispatcher.go
  pkg/channel/distributed/controller/kafkachannel/reconciler.go
  pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
  pkg/channel/distributed/controller/kafkachannel/topic.go
  pkg/channel/distributed/controller/kafkachannel/topic_test.go
  pkg/channel/distributed/controller/kafkasecret/receiver.go
  pkg/channel/distributed/controller/kafkasecretinjection/controller.go
  pkg/channel/distributed/controller/testing/data.go
  pkg/channel/distributed/controller/util/channel.go
  pkg/channel/distributed/controller/util/finalizer.go
  pkg/channel/distributed/controller/util/finalizer_test.go
  pkg/channel/distributed/controller/util/secret.go
  pkg/channel/distributed/controller/util/subscription.go
Labels: approved, cla: yes, lgtm, size/XL

#163 Getting rid of the distributed/common/constants
  pkg/channel/distributed/common/config/configwatcher_test.go
  pkg/channel/distributed/common/config/observability_test.go
  pkg/channel/distributed/common/config/tracing_test.go
  pkg/channel/distributed/common/constants/constants.go
  pkg/channel/distributed/common/k8s/context_test.go
  pkg/channel/distributed/common/kafka/admin/admin.go
  pkg/channel/distributed/common/kafka/admin/admin_kafka_test.go
  pkg/channel/distributed/common/kafka/admin/admin_test.go
  pkg/channel/distributed/common/kafka/sarama/sarama_test.go
  pkg/channel/distributed/common/metrics/stats_reporter_test.go
  pkg/channel/distributed/controller/kafkachannel/channel.go
  pkg/channel/distributed/controller/kafkachannel/controller_test.go
  pkg/channel/distributed/controller/kafkachannel/dispatcher.go
  pkg/channel/distributed/controller/kafkasecret/controller.go
  pkg/channel/distributed/controller/kafkasecret/controller_test.go
  pkg/channel/distributed/controller/kafkasecret/receiver.go
  pkg/channel/distributed/controller/testing/data.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
  pkg/channel/distributed/receiver/producer/producer_test.go
  pkg/common/constants/constants.go
Labels: approved, cla: yes, lgtm, size/M

#146 E2e test distributed
  config/channel/distributed/300-kafka-secret.yaml
  pkg/channel/distributed/Makefile
  pkg/channel/distributed/dispatcher/dispatcher/handler.go
  test/config/README.md
  test/e2e-tests.sh
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#165 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#166 [Automated] Format markdown
  test/config/README.md
Labels: approved, cla: yes, lgtm, size/XS

#168 Port https://github.com/knative/eventing-contrib/pull/1660
  config/channel/consolidated/deployments/dispatcher.yaml
Labels: approved, cla: yes, lgtm, size/XS

#167 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/pkg/channel/message_dispatcher.go
  vendor/knative.dev/eventing/pkg/kncloudevents/http_client.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#169 No longer use deprecated calls
  pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
  pkg/source/adapter/adapter_test.go
Labels: approved, cla: yes, lgtm, size/XS

#170 E2e remove source from distributed
  test/e2e-tests.sh
  test/e2e/kafka_binding_test.go
  test/e2e/kafka_source_reconciler_test.go
  test/e2e/kafka_source_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#172 fix namespaced kafka dispacher crash
  pkg/channel/consolidated/reconciler/controller/resources/dispatcher.go
  pkg/channel/consolidated/reconciler/controller/resources/dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/S

#173 [consolidated] Disable KafkaChannel dispatcher leader election
  cmd/channel/consolidated/dispatcher/main.go
  config/channel/consolidated/roles/dispatcher-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/S

#175 Add defensive coding around reconciling deleted resources.
  pkg/channel/distributed/controller/kafkachannel/channel.go
  pkg/channel/distributed/controller/kafkachannel/dispatcher.go
  pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
  pkg/channel/distributed/controller/kafkasecret/receiver.go
  pkg/channel/distributed/controller/kafkasecret/reconciler_test.go
  pkg/channel/distributed/controller/testing/data.go
  pkg/channel/distributed/controller/util/finalizer.go
  pkg/channel/distributed/controller/util/finalizer_test.go
Labels: approved, cla: yes, lgtm, size/L

#179 [common] don't use session context to send messages
  pkg/common/consumer/consumer_handler.go
Labels: approved, cla: yes, lgtm, size/XS

#177 KafkaSource: set default zap logger level to "info"
  config/source/configmaps/observability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#180 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-conformance-tests.sh
  vendor/knative.dev/eventing/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#183 Add Ahmed Abdalla to reviewers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#184 Add myself as approver and reviewer
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#138 Enable KafkaSource scale subresource
  cmd/source/controller/main.go
  config/source/resources/kafkasource.yaml
  go.sum
  pkg/apis/sources/v1alpha1/kafka_conversion.go
  pkg/apis/sources/v1alpha1/kafka_types.go
  pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/sources/v1beta1/kafka_lifecycle.go
  pkg/apis/sources/v1beta1/kafka_types.go
  pkg/apis/sources/v1beta1/zz_generated.deepcopy.go
  pkg/source/reconciler/source/kafkasource.go
  pkg/source/reconciler/source/resources/receive_adapter.go
Labels: approved, cla: yes, lgtm, size/L

#185 Fix a few more occurrences of divisive language and ignore strimzi files
  .wokeignore
  config/channel/consolidated/placeholder.go
  pkg/channel/distributed/common/kafka/admin/admin_custom_test.go
Labels: approved, cla: yes, lgtm, size/XS

#181 [Consolidated] Use SyncProducer to provide safer delivery
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/M

#191 Update tests to refect we don't have the consumer mode, since ages
  pkg/channel/consolidated/utils/util_test.go
Labels: approved, cla: yes, lgtm, size/M

#190 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_message_handler.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e-upgrade-tests.sh
  vendor/knative.dev/eventing/test/e2e/helpers/broker_redelivery_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_chain_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_dls_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_event_tranformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_single_event_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/parallel_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/sequence_test_helper.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_matchers.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_log.go
  vendor/knative.dev/eventing/test/lib/recordevents/receiver/receiver.go
  vendor/knative.dev/eventing/test/lib/recordevents/receiver/reply.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/constructor.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/recorder.go
  vendor/knative.dev/eventing/test/lib/recordevents/resources.go
  vendor/knative.dev/eventing/test/lib/recordevents/sender/sender.go
  vendor/knative.dev/eventing/test/lib/sender/resources.go
  vendor/knative.dev/eventing/test/test_images/recordevents/main.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/reconciler/testing/tracker.go
  vendor/knative.dev/pkg/test/logging/.gitattributes
  vendor/knative.dev/pkg/test/logging/doc.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/logger.go
  vendor/knative.dev/pkg/test/logging/memory_encoder.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logging/zapr.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#189 Allow changing resync period via environment variable
  cmd/channel/distributed/controller/main.go
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/distributed/common/env/constants.go
  pkg/channel/distributed/common/env/util.go
  pkg/channel/distributed/controller/env/environment.go
  pkg/channel/distributed/controller/env/environment_test.go
  pkg/channel/distributed/controller/kafkachannel/controller_test.go
  pkg/channel/distributed/controller/kafkachannel/dispatcher.go
  pkg/channel/distributed/controller/kafkasecret/controller_test.go
  pkg/channel/distributed/controller/kafkasecret/receiver.go
  pkg/channel/distributed/controller/kafkasecretinformer/kafkasecretinformer.go
  pkg/channel/distributed/controller/kafkasecretinformer/kafkasecretinformer_test.go
  pkg/channel/distributed/controller/testing/data.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel_test.go
  pkg/channel/distributed/dispatcher/env/environment.go
  pkg/channel/distributed/dispatcher/env/environment_test.go
  pkg/channel/distributed/receiver/channel/channel.go
  pkg/channel/distributed/receiver/channel/channel_test.go
  pkg/channel/distributed/receiver/env/environment.go
  pkg/channel/distributed/receiver/env/environment_test.go
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#193 Check debug logging
  cmd/channel/distributed/receiver/main.go
  pkg/channel/distributed/dispatcher/dispatcher/handler.go
  pkg/channel/distributed/receiver/producer/producer.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#194 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/test/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#197 [Automated] Format markdown
  README.md
  config/channel/distributed/README.md
Labels: approved, cla: yes, lgtm, size/XS

#198 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#192 Adding global TLS/SASL for the consolidated KafkaChannel
  config/channel/consolidated/configmaps/kafka-config.yaml
  config/channel/consolidated/roles/controller-clusterrole.yaml
  config/channel/consolidated/roles/dispatcher-clusterrole.yaml
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/resources/client.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
  pkg/channel/consolidated/utils/util.go
  pkg/channel/consolidated/utils/util_test.go
  pkg/common/client.go
  pkg/common/client_test.go
  pkg/source/adapter/adapter.go
  test/config/100-kafka-ephemeral-triple-2.6.0.yaml
  test/config/100-strimzi-users-0.20.0.yaml
  test/config/config-kafka-sasl.yaml
  test/config/config-kafka-tls.yaml
  test/e2e-tests.sh
  test/test_images/kafka-publisher/main.go
Labels: approved, cla: yes, lgtm, size/XL

#201 SASL: Using scram-sha-512 and scram-sha-256 support
  go.mod
  go.sum
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/utils/util.go
  pkg/source/adapter/adapter.go
  pkg/source/client.go
  pkg/source/client_test.go
  pkg/source/kafka_scram_client.go
  test/config/100-strimzi-users-0.20.0.yaml
  test/e2e-tests.sh
  test/test_images/kafka-publisher/main.go
  third_party/VENDOR-LICENSE/github.com/xdg/scram/LICENSE
  third_party/VENDOR-LICENSE/github.com/xdg/stringprep/LICENSE
  vendor/github.com/xdg/scram/.gitignore
  vendor/github.com/xdg/scram/.travis.yml
  vendor/github.com/xdg/scram/LICENSE
  vendor/github.com/xdg/scram/README.md
  vendor/github.com/xdg/scram/client.go
  vendor/github.com/xdg/scram/client_conv.go
  vendor/github.com/xdg/scram/common.go
  vendor/github.com/xdg/scram/doc.go
  vendor/github.com/xdg/scram/parse.go
  vendor/github.com/xdg/scram/scram.go
  vendor/github.com/xdg/scram/server.go
  vendor/github.com/xdg/scram/server_conv.go
  vendor/github.com/xdg/stringprep/.gitignore
  vendor/github.com/xdg/stringprep/.travis.yml
  vendor/github.com/xdg/stringprep/LICENSE
  vendor/github.com/xdg/stringprep/README.md
  vendor/github.com/xdg/stringprep/bidi.go
  vendor/github.com/xdg/stringprep/doc.go
  vendor/github.com/xdg/stringprep/error.go
  vendor/github.com/xdg/stringprep/map.go
  vendor/github.com/xdg/stringprep/profile.go
  vendor/github.com/xdg/stringprep/saslprep.go
  vendor/github.com/xdg/stringprep/set.go
  vendor/github.com/xdg/stringprep/tables.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#199 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/doc.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/channel/config.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/fake/fake_pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/fake/fake_sources_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/sources_client.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/v1beta2/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/v1beta2/pingsource.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1beta2/expansion_generated.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1beta2/pingsource.go
  vendor/knative.dev/eventing/pkg/configmap/reader.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/pingsource.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/pingsource.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e-conformance-tests.sh
  vendor/knative.dev/eventing/test/e2e-tests.sh
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/hack/update-k8s-deps.sh
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#204 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#203 Use the latest version of the Shopify Sarama client lib
  go.mod
  go.sum
  pkg/channel/distributed/common/kafka/sarama/sarama_test.go
  vendor/github.com/Shopify/sarama/CHANGELOG.md
  vendor/github.com/Shopify/sarama/async_producer.go
  vendor/github.com/Shopify/sarama/client.go
  vendor/github.com/Shopify/sarama/config.go
  vendor/github.com/Shopify/sarama/consumer.go
  vendor/github.com/Shopify/sarama/dev.yml
  vendor/github.com/Shopify/sarama/go.mod
  vendor/github.com/Shopify/sarama/go.sum
  vendor/github.com/Shopify/sarama/mockresponses.go
  vendor/github.com/Shopify/sarama/utils.go
  vendor/github.com/klauspost/compress/huff0/bitwriter.go
  vendor/github.com/klauspost/compress/huff0/compress.go
  vendor/github.com/klauspost/compress/huff0/decompress.go
  vendor/github.com/klauspost/compress/huff0/huff0.go
  vendor/github.com/klauspost/compress/zstd/README.md
  vendor/github.com/klauspost/compress/zstd/blockdec.go
  vendor/github.com/klauspost/compress/zstd/blockenc.go
  vendor/github.com/klauspost/compress/zstd/decoder.go
  vendor/github.com/klauspost/compress/zstd/dict.go
  vendor/github.com/klauspost/compress/zstd/enc_base.go
  vendor/github.com/klauspost/compress/zstd/enc_better.go
  vendor/github.com/klauspost/compress/zstd/enc_dfast.go
  vendor/github.com/klauspost/compress/zstd/enc_fast.go
  vendor/github.com/klauspost/compress/zstd/enc_params.go
  vendor/github.com/klauspost/compress/zstd/encoder.go
  vendor/github.com/klauspost/compress/zstd/encoder_options.go
  vendor/github.com/klauspost/compress/zstd/frameenc.go
  vendor/github.com/klauspost/compress/zstd/history.go
  vendor/github.com/klauspost/compress/zstd/seqdec.go
  vendor/github.com/klauspost/compress/zstd/snappy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#205 Move AuthConfig code to one place and add tests
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/utils/util.go
  pkg/source/client.go
  pkg/source/client_test.go
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#202 Upconvert kafka errors to sarama TopicError
  pkg/channel/distributed/common/kafka/admin/admin_eventhub.go
  pkg/channel/distributed/common/kafka/admin/util/util.go
  pkg/channel/distributed/common/kafka/admin/util/util_test.go
  pkg/channel/distributed/controller/kafkachannel/topic.go
Labels: approved, cla: yes, lgtm, size/M

#206 Update component for high-availability election bucket naming
  config/channel/distributed/300-leaderelection-configmap.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#210 ACK new test jobs
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#209 Defaulting to SASL plaintext wasn't working for consolidated channel
  pkg/source/client.go
  pkg/source/client_test.go
Labels: approved, cla: yes, lgtm, size/M

#208 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#207 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#212 fix half-baked table tests
  pkg/channel/distributed/common/k8s/util_test.go
  pkg/channel/distributed/controller/config/config_test.go
  pkg/channel/distributed/controller/env/environment_test.go
  pkg/channel/distributed/controller/util/dispatcher_test.go
  pkg/channel/distributed/controller/util/dns_test.go
  pkg/channel/distributed/controller/util/hash_test.go
  pkg/channel/distributed/dispatcher/env/environment_test.go
  pkg/channel/distributed/receiver/env/environment_test.go
Labels: approved, cla: yes, lgtm, size/L

#213 Ensure we do not accidently run the consolidated plain tests with AUTH is enabled
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#216 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/webhook/env.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#211 [0.19] Backport: Adding global TLS/SASL for the consolidated KafkaChannel
  config/channel/consolidated/configmaps/kafka-config.yaml
  config/channel/consolidated/roles/controller-clusterrole.yaml
  config/channel/consolidated/roles/dispatcher-clusterrole.yaml
  go.mod
  go.sum
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/dispatcher_test.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/resources/client.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
  pkg/channel/consolidated/utils/util.go
  pkg/channel/consolidated/utils/util_test.go
  pkg/source/adapter/adapter.go
  pkg/source/client.go
  pkg/source/client_test.go
  pkg/source/kafka_scram_client.go
  test/config/100-kafka-ephemeral-triple-2.6.0.yaml
  test/config/100-strimzi-users-0.20.0.yaml
  test/config/config-kafka-sasl.yaml
  test/config/config-kafka-tls.yaml
  test/e2e-tests.sh
  third_party/VENDOR-LICENSE/github.com/xdg/scram/LICENSE
  third_party/VENDOR-LICENSE/github.com/xdg/stringprep/LICENSE
  vendor/github.com/xdg/scram/.gitignore
  vendor/github.com/xdg/scram/.travis.yml
  vendor/github.com/xdg/scram/LICENSE
  vendor/github.com/xdg/scram/README.md
  vendor/github.com/xdg/scram/client.go
  vendor/github.com/xdg/scram/client_conv.go
  vendor/github.com/xdg/scram/common.go
  vendor/github.com/xdg/scram/doc.go
  vendor/github.com/xdg/scram/parse.go
  vendor/github.com/xdg/scram/scram.go
  vendor/github.com/xdg/scram/server.go
  vendor/github.com/xdg/scram/server_conv.go
  vendor/github.com/xdg/stringprep/.gitignore
  vendor/github.com/xdg/stringprep/.travis.yml
  vendor/github.com/xdg/stringprep/LICENSE
  vendor/github.com/xdg/stringprep/README.md
  vendor/github.com/xdg/stringprep/bidi.go
  vendor/github.com/xdg/stringprep/doc.go
  vendor/github.com/xdg/stringprep/error.go
  vendor/github.com/xdg/stringprep/map.go
  vendor/github.com/xdg/stringprep/profile.go
  vendor/github.com/xdg/stringprep/saslprep.go
  vendor/github.com/xdg/stringprep/set.go
  vendor/github.com/xdg/stringprep/tables.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#217 Use namespace var, instead of hardcoded value
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#225 Use webhook name from common pkg
  cmd/webhook/main.go
  vendor/knative.dev/eventing/pkg/logconfig/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#226 [distributed] Use same configmap name, for the channels
  config/channel/distributed/300-eventing-kafka-configmap.yaml
  pkg/channel/distributed/common/config/configwatcher.go
  pkg/channel/distributed/common/config/constants.go
  pkg/channel/distributed/common/kafka/sarama/sarama.go
  pkg/channel/distributed/common/testing/constants.go
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#228 Skipping a flaky test
  pkg/channel/distributed/common/metrics/stats_reporter_test.go
Labels: approved, cla: yes, lgtm, size/XS

#132 Use CRD v1 API for KafkaChannel, KafkaSource and KafkaBinding
  config/channel/resources/kafkachannel-crd.yaml
  config/source/resources/kafkabinding.yaml
  config/source/resources/kafkasource.yaml
Labels: approved, cla: yes, lgtm, size/L

#230 Update Webhook Api to v1
  config/channel/webhook/webhook-configuration.yaml
  config/source/webhooks/kafka.yaml
Labels: approved, cla: yes, lgtm, size/M

#223 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  vendor/knative.dev/eventing/test/e2e-tests.sh
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#234 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/injection/client/client.go
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#231 Go with the overall default of the leader election
  config/channel/consolidated/configmaps/leader-election.yaml
  config/channel/consolidated/deployments/controller.yaml
  config/channel/consolidated/deployments/dispatcher.yaml
  config/channel/distributed/300-leaderelection-configmap.yaml
  config/channel/distributed/500-controller-deployment.yaml
  config/source/configmaps/leader-election.yaml
  config/source/deployments/controller.yaml
  pkg/channel/consolidated/reconciler/controller/resources/dispatcher.go
  pkg/channel/consolidated/reconciler/controller/resources/dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/S

#235 Remove configs with no concrete value/override
  config/channel/consolidated/400-leader-election-config.yaml
  config/channel/consolidated/configmaps/leader-election.yaml
  config/channel/distributed/300-leaderelection-configmap.yaml
  config/source/config-leader-election.yaml
  config/source/configmaps/leader-election.yaml
Labels: approved, cla: yes, lgtm, size/L

#236 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_conversion.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e-upgrade-tests.sh
  vendor/knative.dev/eventing/test/presubmit-tests.sh
  vendor/knative.dev/pkg/webhook/psbinding/index.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#238 Move common stuff from e2e-tests.sh into e2e-common.sh
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XL

#237 Add kafkaSource saslType, e2e tests for auth (tls and sasl512)
  pkg/apis/bindings/v1alpha1/kafka_conversion.go
  pkg/apis/bindings/v1alpha1/kafka_conversion_test.go
  pkg/apis/bindings/v1alpha1/kafka_lifecycle.go
  pkg/apis/bindings/v1alpha1/kafka_lifecycle_test.go
  pkg/apis/bindings/v1alpha1/kafka_types.go
  pkg/apis/bindings/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/bindings/v1beta1/kafka_lifecycle.go
  pkg/apis/bindings/v1beta1/kafka_lifecycle_test.go
  pkg/apis/bindings/v1beta1/kafka_types.go
  pkg/apis/bindings/v1beta1/zz_generated.deepcopy.go
  pkg/source/client.go
  pkg/source/client_test.go
  pkg/source/reconciler/source/resources/receive_adapter.go
  pkg/source/reconciler/source/resources/receive_adapter_test.go
  test/e2e-tests.sh
  test/e2e/kafka_binding_test.go
  test/e2e/kafka_source_reconciler_test.go
  test/e2e/kafka_source_test.go
Labels: approved, cla: yes, lgtm, size/XL

#241 Add kafkaSource saslType, e2e tests for auth (tls and sasl512) (#237)
  pkg/apis/bindings/v1alpha1/kafka_conversion.go
  pkg/apis/bindings/v1alpha1/kafka_conversion_test.go
  pkg/apis/bindings/v1alpha1/kafka_lifecycle.go
  pkg/apis/bindings/v1alpha1/kafka_lifecycle_test.go
  pkg/apis/bindings/v1alpha1/kafka_types.go
  pkg/apis/bindings/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/bindings/v1beta1/kafka_lifecycle.go
  pkg/apis/bindings/v1beta1/kafka_lifecycle_test.go
  pkg/apis/bindings/v1beta1/kafka_types.go
  pkg/apis/bindings/v1beta1/zz_generated.deepcopy.go
  pkg/source/client.go
  pkg/source/client_test.go
  pkg/source/reconciler/source/resources/receive_adapter.go
  pkg/source/reconciler/source/resources/receive_adapter_test.go
  test/e2e-tests.sh
  test/e2e/kafka_binding_test.go
  test/e2e/kafka_source_reconciler_test.go
  test/e2e/kafka_source_test.go
Labels: approved, cla: yes, lgtm, size/XL
