Repository knative-extensions/eventing-kafka, pull requests merged in 2020-05, with the labels that each got.

#17 Adding approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/S

#19 Adding myself to owners
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#20 Handle missing or invalid kafka secrets
  Makefile
  pkg/common/kafka/admin/admin_kafka.go
  pkg/common/kafka/admin/admin_kafka_test.go
Labels: approved, cla: yes, lgtm, size/L
