Repository knative-extensions/eventing-kafka, pull requests merged in 2020-12, with the labels that each got.

#242 Fix label consistency
  pkg/source/reconciler/source/resources/labels.go
  pkg/source/reconciler/source/resources/labels_test.go
  test/e2e/helpers/kafka_helper.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#243 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#244 [Backport] fix label consistency
  pkg/source/reconciler/source/resources/labels.go
  pkg/source/reconciler/source/resources/labels_test.go
  test/e2e/helpers/kafka_helper.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#182 Set subscription readiness based on consumer group status
  cmd/channel/consolidated/dispatcher/main.go
  pkg/channel/consolidated/kafka/admin.go
  pkg/channel/consolidated/kafka/admin_test.go
  pkg/channel/consolidated/reconciler/controller/consumer_group_watcher.go
  pkg/channel/consolidated/reconciler/controller/consumer_group_watcher_test.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel_test.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
  pkg/channel/consolidated/reconciler/testing/kafkachannel.go
Labels: approved, cla: yes, lgtm, size/XL

#239 Close request body for tcp connection reuse
  pkg/source/adapter/adapter.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#220 Use SYSTEM_NAMESPACE variable instead of hardcoded value
  cmd/channel/distributed/controller/main.go
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  pkg/channel/distributed/common/config/configwatcher.go
  pkg/channel/distributed/common/config/configwatcher_test.go
  pkg/channel/distributed/common/config/observability.go
  pkg/channel/distributed/common/config/observability_test.go
  pkg/channel/distributed/common/config/tracing.go
  pkg/channel/distributed/common/config/tracing_test.go
  pkg/channel/distributed/common/k8s/context_test.go
  pkg/channel/distributed/common/kafka/admin/admin.go
  pkg/channel/distributed/common/kafka/admin/admin_kafka_test.go
  pkg/channel/distributed/common/kafka/admin/admin_test.go
  pkg/channel/distributed/common/kafka/sarama/sarama_test.go
  pkg/channel/distributed/common/metrics/stats_reporter_test.go
  pkg/channel/distributed/common/testing/constants.go
  pkg/channel/distributed/common/testing/util.go
  pkg/channel/distributed/controller/env/environment.go
  pkg/channel/distributed/controller/env/environment_test.go
  pkg/channel/distributed/controller/kafkachannel/channel.go
  pkg/channel/distributed/controller/kafkachannel/controller.go
  pkg/channel/distributed/controller/kafkachannel/controller_test.go
  pkg/channel/distributed/controller/kafkachannel/dispatcher.go
  pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
  pkg/channel/distributed/controller/kafkasecret/controller.go
  pkg/channel/distributed/controller/kafkasecret/controller_test.go
  pkg/channel/distributed/controller/kafkasecret/receiver.go
  pkg/channel/distributed/controller/kafkasecret/reconciler_test.go
  pkg/channel/distributed/controller/kafkasecretinformer/kafkasecretinformer_test.go
  pkg/channel/distributed/controller/testing/data.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
  pkg/channel/distributed/dispatcher/env/environment.go
  pkg/channel/distributed/dispatcher/env/environment_test.go
  pkg/channel/distributed/receiver/env/environment.go
  pkg/channel/distributed/receiver/env/environment_test.go
  pkg/channel/distributed/receiver/producer/producer_test.go
  pkg/common/constants/constants.go
  test/config/config-tracing.yaml
  test/config/monitoring.yaml
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#247 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#248 Usage of more SYSTEM_NAMESAPCE in tests
  test/config/config-kafka-sasl.yaml
  test/config/config-kafka-tls.yaml
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/S

#249 Backport: Set subscription readiness based on consumer group status (#182)
  cmd/channel/consolidated/dispatcher/main.go
  pkg/channel/consolidated/kafka/admin.go
  pkg/channel/consolidated/kafka/admin_test.go
  pkg/channel/consolidated/reconciler/controller/consumer_group_watcher.go
  pkg/channel/consolidated/reconciler/controller/consumer_group_watcher_test.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel_test.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
  pkg/channel/consolidated/reconciler/testing/kafkachannel.go
Labels: approved, cla: yes, lgtm, size/XL

#246 Fix flaky metrics, health, and observability tests
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  pkg/channel/distributed/common/config/observability.go
  pkg/channel/distributed/common/config/observability_test.go
  pkg/channel/distributed/common/health/health.go
  pkg/channel/distributed/common/health/health_test.go
  pkg/channel/distributed/common/metrics/stats_reporter.go
  pkg/channel/distributed/common/metrics/stats_reporter_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#251 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#253 Increase health check timeouts to allow Sarama timeouts
  pkg/channel/distributed/controller/constants/constants.go
  pkg/channel/distributed/receiver/producer/producer.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#252 Integrate the gopath hacks
  hack/update-codegen.sh
Labels: approved, cla: yes, lgtm, size/S

#256 Removing verbose info logger
  pkg/channel/consolidated/kafka/admin.go
Labels: approved, cla: yes, lgtm, size/XS

#257 Granting RBAC access for the leases
  config/channel/consolidated/roles/dispatcher-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/S

#258 [0.19] some backports
  config/channel/consolidated/roles/dispatcher-clusterrole.yaml
  pkg/channel/consolidated/kafka/admin.go
Labels: approved, cla: yes, lgtm, size/S

#255 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/.gitignore
  vendor/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/README.md
  vendor/github.com/blendle/zapdriver/config.go
  vendor/github.com/blendle/zapdriver/core.go
  vendor/github.com/blendle/zapdriver/encoder.go
  vendor/github.com/blendle/zapdriver/go.mod
  vendor/github.com/blendle/zapdriver/go.sum
  vendor/github.com/blendle/zapdriver/http.go
  vendor/github.com/blendle/zapdriver/label.go
  vendor/github.com/blendle/zapdriver/logger.go
  vendor/github.com/blendle/zapdriver/operation.go
  vendor/github.com/blendle/zapdriver/report.go
  vendor/github.com/blendle/zapdriver/service.go
  vendor/github.com/blendle/zapdriver/source.go
  vendor/github.com/blendle/zapdriver/trace.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#263 fix custom consumer group error channel lifecycle
  pkg/common/consumer/consumer_factory.go
  pkg/common/consumer/consumer_factory_test.go
  pkg/common/consumer/consumer_handler.go
  pkg/common/consumer/consumer_handler_test.go
Labels: approved, cla: yes, lgtm, size/M

#262 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/duck/resource_getters.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#265 Fix error format in adapter
  pkg/source/adapter/adapter.go
Labels: approved, cla: yes, lgtm, size/XS

#266 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/helper.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#267 Better reflection of this artifact on the release labels
  config/channel/consolidated/200-controller-serviceaccount.yaml
  config/channel/consolidated/200-dispatcher-serviceaccount.yaml
  config/channel/consolidated/201-clusterrolebinding.yaml
  config/channel/consolidated/deployments/controller.yaml
  config/channel/consolidated/deployments/dispatcher.yaml
  config/channel/consolidated/roles/addressable-resolver-clusterrole.yaml
  config/channel/consolidated/roles/channelable-manipulator-clusterrole.yaml
  config/channel/consolidated/roles/controller-clusterrole.yaml
  config/channel/consolidated/roles/dispatcher-clusterrole.yaml
  config/channel/distributed/100-addressable-resolver-clusterrole.yaml
  config/channel/resources/kafkachannel-crd.yaml
  config/channel/webhook/webhook-clusterrole.yaml
  config/channel/webhook/webhook-clusterrolebinding.yaml
  config/channel/webhook/webhook-configuration.yaml
  config/channel/webhook/webhook-deployment.yaml
  config/channel/webhook/webhook-secret.yaml
  config/channel/webhook/webhook-service.yaml
  config/channel/webhook/webhook-serviceaccount.yaml
  config/source/100-deprecated-namespace.yaml
  config/source/100-namespace.yaml
  config/source/200-serviceaccount.yaml
  config/source/202-clusterrolebinding.yaml
  config/source/500-deprecated-controller.yaml
  config/source/deployments/controller-service.yaml
  config/source/deployments/controller.yaml
  config/source/resources/kafkabinding.yaml
  config/source/resources/kafkasource.yaml
  config/source/roles/clusterrole.yaml
  config/source/webhooks/kafka.yaml
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/M

#269 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#270 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#271 Change auto topic create to be false...
  test/config/100-kafka-ephemeral-triple-2.6.0.yaml
Labels: approved, cla: yes, lgtm, size/XS

#272 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#273 Read resp body for connection reuse
  pkg/source/adapter/adapter.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#275 Remove default limits
  config/channel/distributed/300-eventing-kafka-configmap.yaml
  config/channel/distributed/500-controller-deployment.yaml
  pkg/channel/distributed/common/kafka/sarama/sarama_test.go
  pkg/channel/distributed/controller/config/config.go
  pkg/channel/distributed/controller/config/config_test.go
  pkg/channel/distributed/controller/kafkachannel/dispatcher.go
  pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
  pkg/channel/distributed/controller/kafkasecret/receiver.go
  pkg/channel/distributed/controller/kafkasecret/reconciler_test.go
  pkg/channel/distributed/controller/testing/data.go
  pkg/channel/distributed/controller/testing/factory.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#281 We forgot one admissionregistration.k8s.io/v1beta1 update to v1
  config/source/webhooks/kafka.yaml
Labels: approved, cla: yes, lgtm, size/XS

#282 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#283 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#278 Move Sarama YAML related functions into common
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  pkg/channel/distributed/common/kafka/admin/admin_kafka.go
  pkg/channel/distributed/common/kafka/consumer/consumer_test.go
  pkg/channel/distributed/common/kafka/producer/producer_test.go
  pkg/channel/distributed/common/kafka/sarama/sarama.go
  pkg/channel/distributed/common/kafka/sarama/sarama_test.go
  pkg/channel/distributed/controller/kafkachannel/reconciler.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/receiver/producer/producer.go
  pkg/common/client/config.go
  pkg/common/client/config_test.go
  pkg/common/client/sarama.go
  pkg/common/client/sarama_test.go
Labels: approved, cla: yes, lgtm, size/XL

#284 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#287 Prepare for splitting configmap package.
  go.mod
  go.sum
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
  pkg/channel/distributed/common/config/observability.go
  pkg/channel/distributed/common/config/observability_test.go
  pkg/channel/distributed/common/config/tracing.go
  pkg/channel/distributed/common/k8s/context.go
  vendor/knative.dev/pkg/configmap/informer/informed_watcher.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/test/mako/config/slack.go
  vendor/knative.dev/pkg/tracing/setup.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
