Repository knative-extensions/eventing-kafka, pull requests merged in 2020-09, with the labels that each got.

#47 Pluggable admin client
  cmd/channel/main.go
  cmd/dispatcher/main.go
  config/200-eventing-kafka-configmap.yaml
  config/400-deployment.yaml
  config/README.md
  go.sum
  pkg/channel/env/environment.go
  pkg/channel/producer/producer.go
  pkg/common/config/configwatcher.go
  pkg/common/env/constants.go
  pkg/common/kafka/README.md
  pkg/common/kafka/admin/admin.go
  pkg/common/kafka/admin/admin_custom.go
  pkg/common/kafka/admin/admin_custom_test.go
  pkg/common/kafka/admin/admin_eventhub.go
  pkg/common/kafka/admin/admin_kafka.go
  pkg/common/kafka/admin/admin_kafka_test.go
  pkg/common/kafka/admin/admin_test.go
  pkg/common/kafka/admin/custom/constants.go
  pkg/common/kafka/admin/custom/topic_detail.go
  pkg/common/kafka/admin/custom/topic_detail_test.go
  pkg/common/kafka/constants/constants.go
  pkg/common/kafka/consumer/consumer_test.go
  pkg/common/kafka/producer/producer_test.go
  pkg/common/kafka/sarama/sarama.go
  pkg/common/kafka/sarama/sarama_test.go
  pkg/common/testing/constants.go
  pkg/common/testing/util.go
  pkg/controller/README.md
  pkg/controller/config/config.go
  pkg/controller/config/config_test.go
  pkg/controller/constants/constants.go
  pkg/controller/env/environment.go
  pkg/controller/env/environment_test.go
  pkg/controller/kafkachannel/controller.go
  pkg/controller/kafkachannel/reconciler.go
  pkg/controller/kafkachannel/topic.go
  pkg/controller/test/data.go
  pkg/dispatcher/dispatcher/dispatcher.go
  pkg/dispatcher/env/environment.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#51 Use server flag for kubernetes server url
  cmd/channel/main.go
  cmd/dispatcher/main.go
Labels: approved, cla: yes, lgtm, size/S

#55 Improve dispatcher naming
  pkg/controller/test/data.go
  pkg/controller/util/channel.go
  pkg/controller/util/channel_test.go
  pkg/controller/util/dispatcher.go
  pkg/controller/util/dispatcher_test.go
  pkg/controller/util/hash.go
  pkg/controller/util/hash_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#56 enable code coverage
  .codecov.yaml
Labels: approved, cla: yes, lgtm, size/XS

#62 add POD_NAME env var to distributed channel controller deployment
  config/channel/distributed/400-deployment.yaml
Labels: approved, cla: yes, lgtm, size/XS

#64 Refactor configmap comparison
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  go.mod
  pkg/channel/distributed/common/config/configwatcher.go
  pkg/channel/distributed/common/config/configwatcher_test.go
  pkg/channel/distributed/common/env/util_test.go
  pkg/channel/distributed/common/kafka/admin/admin.go
  pkg/channel/distributed/common/kafka/admin/admin_kafka_test.go
  pkg/channel/distributed/common/kafka/admin/admin_test.go
  pkg/channel/distributed/common/kafka/admin/util/util.go
  pkg/channel/distributed/common/kafka/consumer/consumer_test.go
  pkg/channel/distributed/common/kafka/producer/producer_test.go
  pkg/channel/distributed/common/kafka/sarama/sarama.go
  pkg/channel/distributed/common/kafka/sarama/sarama_test.go
  pkg/channel/distributed/common/testing/util.go
  pkg/channel/distributed/controller/config/config_test.go
  pkg/channel/distributed/controller/env/environment_test.go
  pkg/channel/distributed/controller/kafkachannel/channel.go
  pkg/channel/distributed/controller/kafkachannel/dispatcher.go
  pkg/channel/distributed/controller/kafkachannel/reconciler.go
  pkg/channel/distributed/controller/kafkasecret/channel.go
  pkg/channel/distributed/controller/test/data.go
  pkg/channel/distributed/controller/util/dns.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
  pkg/channel/distributed/dispatcher/dispatcher/handler.go
  pkg/channel/distributed/dispatcher/testing/mocks.go
  pkg/channel/distributed/receiver/producer/producer.go
  pkg/channel/distributed/receiver/producer/producer_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL
