Repository knative-extensions/eventing-kafka, pull requests merged in 2020-10, with the labels that each got.

#77 Update linter
  pkg/channel/distributed/common/kafka/admin/admin_eventhub_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#80 Some fmt lints
  contrib/test/e2e/helpers/kafka_helper.go
  contrib/test/lib/creation.go
  pkg/channel/consolidated/reconciler/controller/resources/service.go
  pkg/channel/distributed/common/health/health.go
  pkg/channel/distributed/common/health/health_test.go
  pkg/channel/distributed/common/k8s/util_test.go
  pkg/channel/distributed/common/kafka/admin/admin_custom_test.go
  pkg/channel/distributed/common/kafka/admin/admin_eventhub.go
  pkg/channel/distributed/common/kafka/admin/admin_eventhub_test.go
  pkg/channel/distributed/common/kafka/admin/eventhubcache/cache.go
  pkg/channel/distributed/common/kafka/admin/eventhubcache/cache_test.go
  pkg/channel/distributed/common/kafka/admin/eventhubcache/hubmanager.go
  pkg/channel/distributed/common/kafka/admin/eventhubcache/namespace_test.go
  pkg/channel/distributed/common/kafka/testing/mocks.go
  pkg/channel/distributed/common/metrics/stats_reporter.go
  pkg/channel/distributed/common/util/util.go
  pkg/channel/distributed/common/util/util_test.go
  pkg/channel/distributed/controller/kafkasecretinjection/reconciler.go
  pkg/channel/distributed/controller/kafkasecretinjection/state.go
  pkg/channel/distributed/controller/util/dns_test.go
  pkg/channel/distributed/controller/util/secret_test.go
  pkg/channel/distributed/dispatcher/dispatcher/handler.go
  pkg/channel/distributed/dispatcher/health/health_test.go
  pkg/channel/distributed/receiver/health/health_test.go
  pkg/channel/distributed/receiver/test/message.go
  pkg/channel/distributed/receiver/util/util_test.go
Labels: approved, cla: yes, lgtm, size/M

#82 Respect that we have different things to release now
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/M

#84 Relocation, part x: Move src client
  contrib/kafka/source/PROJECT
  contrib/kafka/source/README.md
  contrib/test/test_images/kafka-publisher/main.go
  pkg/source/adapter/adapter.go
  pkg/source/client.go
  pkg/source/client_test.go
  third_party/VENDOR-LICENSE/knative.dev/eventing-kafka/contrib/test/LICENSE
Labels: approved, cla: yes, lgtm, size/M

#81 Porting 4169 to here
  config/channel/consolidated/deployments/webhook.yaml
  config/source/deployments/controller.yaml
Labels: approved, cla: yes, lgtm, size/XS

#83 Move docs for metrics
  docs/metrics.md
Labels: approved, cla: yes, lgtm, size/XS

#85 the hack content was moved over
  contrib/hack/boilerplate.go.txt
  contrib/hack/update-codegen.sh
  contrib/hack/update-deps.sh
  contrib/hack/update-k8s-deps.sh
  contrib/hack/verify-codegen.sh
Labels: approved, cla: yes, lgtm, size/L

#87 Add POD_NAME to consolidated channel deployments
  config/channel/consolidated/deployments/controller.yaml
  config/channel/consolidated/deployments/dispatcher.yaml
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/XS

#88 Remove the old tmp folder
  contrib/AUTHORS
  contrib/CODE_OF_CONDUCT.md
  contrib/CONTRIBUTING.md
  contrib/DEVELOPMENT.md
  contrib/LICENSE
  contrib/kafka/README.md
Labels: approved, cla: yes, lgtm, size/L

#89 Add top level README and other useful info.
  README.md
  docs/kind_kafka_cluster.md
Labels: approved, cla: yes, lgtm, size/L

#93 refactor test/ dirs to testing/ for inclusion in coverage skip rules
  .gitattributes
  README.md
  config/channel/distributed/200-eventing-kafka-configmap.yaml
  config/channel/distributed/README.md
  pkg/channel/distributed/common/kafka/producer/producer_test.go
  pkg/channel/distributed/controller/kafkachannel/controller_test.go
  pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
  pkg/channel/distributed/controller/kafkachannel/topic_test.go
  pkg/channel/distributed/controller/kafkasecret/controller_test.go
  pkg/channel/distributed/controller/kafkasecret/reconciler_test.go
  pkg/channel/distributed/controller/testing/data.go
  pkg/channel/distributed/controller/testing/factory.go
  pkg/channel/distributed/controller/testing/lister.go
  pkg/channel/distributed/controller/testing/mock.go
  pkg/channel/distributed/receiver/channel/channel_test.go
  pkg/channel/distributed/receiver/producer/producer_test.go
  pkg/channel/distributed/receiver/testing/channel.go
  pkg/channel/distributed/receiver/testing/constants.go
  pkg/channel/distributed/receiver/testing/event.go
  pkg/channel/distributed/receiver/testing/message.go
  pkg/channel/distributed/receiver/testing/mock.go
Labels: approved, cla: yes, lgtm, size/XL

#92 Update readmes
  pkg/channel/consolidated/README.md
  pkg/source/README.md
Labels: approved, cla: yes, lgtm, size/M

#95 Align the config with the others on the same namespace
  config/source/configmaps/observability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#94 refactor kafka producer from being called a channel to a receiver.
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  config/channel/distributed/200-eventing-kafka-configmap.yaml
  config/channel/distributed/400-deployment.yaml
  config/channel/distributed/README.md
  pkg/channel/distributed/README.md
  pkg/channel/distributed/common/config/configwatcher.go
  pkg/channel/distributed/common/k8s/context.go
  pkg/channel/distributed/common/kafka/sarama/sarama_test.go
  pkg/channel/distributed/controller/config/config.go
  pkg/channel/distributed/controller/config/config_test.go
  pkg/channel/distributed/controller/constants/constants.go
  pkg/channel/distributed/controller/env/environment.go
  pkg/channel/distributed/controller/env/environment_test.go
  pkg/channel/distributed/controller/event/event.go
  pkg/channel/distributed/controller/event/event_test.go
  pkg/channel/distributed/controller/kafkachannel/channel.go
  pkg/channel/distributed/controller/kafkachannel/controller_test.go
  pkg/channel/distributed/controller/kafkachannel/dispatcher.go
  pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
  pkg/channel/distributed/controller/kafkachannel/topic_test.go
  pkg/channel/distributed/controller/kafkasecret/controller_test.go
  pkg/channel/distributed/controller/kafkasecret/receiver.go
  pkg/channel/distributed/controller/kafkasecret/reconciler.go
  pkg/channel/distributed/controller/kafkasecret/reconciler_test.go
  pkg/channel/distributed/controller/testing/data.go
  pkg/channel/distributed/controller/util/channel.go
  pkg/channel/distributed/controller/util/channel_test.go
  pkg/channel/distributed/dispatcher/constants/constants.go
  pkg/channel/distributed/receiver/README.md
  pkg/channel/distributed/receiver/constants/constants.go
  pkg/channel/distributed/receiver/env/environment.go
  pkg/channel/distributed/receiver/testing/constants.go
Labels: approved, cla: yes, lgtm, size/XL

#96 Fix release labels in Kafka components
  config/channel/consolidated/deployments/dispatcher.yaml
  config/source/configmaps/observability.yaml
  config/source/roles/clusterrole.yaml
  config/source/webhooks/kafka.yaml
Labels: approved, cla: yes, lgtm, size/S

#99 use knative/pkg utils
  pkg/source/reconciler/source/kafkasource.go
  pkg/source/reconciler/source/resources/receive_adapter.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#104 running misspell
  config/channel/distributed/200-eventing-kafka-configmap.yaml
  pkg/channel/distributed/dispatcher/README.md
  pkg/channel/distributed/receiver/README.md
  test/config/100-strimzi-cluster-operator-0.19.0.yaml
Labels: approved, cla: yes, lgtm, size/S

#102 Remove transformevents and sequencestepper
  hack/tools.go
  test/config/config-tracing.yaml
  test/config/monitoring.yaml
  test/e2e-tests.sh
  vendor/knative.dev/eventing/test/test_images/sequencestepper/main.go
  vendor/knative.dev/eventing/test/test_images/sequencestepper/pod.yaml
  vendor/knative.dev/eventing/test/test_images/transformevents/main.go
  vendor/knative.dev/eventing/test/test_images/transformevents/pod.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#103 Move constants to common for clean dependency graph.
  pkg/apis/messaging/v1alpha1/kafka_channel_defaults.go
  pkg/apis/messaging/v1alpha1/kafka_channel_defaults_test.go
  pkg/apis/messaging/v1beta1/kafka_channel_defaults.go
  pkg/apis/messaging/v1beta1/kafka_channel_defaults_test.go
  pkg/channel/consolidated/utils/util.go
  pkg/common/constants/constants.go
Labels: approved, cla: yes, lgtm, size/M

#110 Drop unnecessary pin of go-autorest
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#120 [Automated] Format markdown
  README.md
  config/channel/distributed/README.md
  docs/kind_kafka_cluster.md
  pkg/channel/consolidated/README.md
  pkg/channel/distributed/README.md
  pkg/channel/distributed/common/kafka/README.md
  pkg/channel/distributed/common/metrics/README.md
  pkg/channel/distributed/controller/README.md
  pkg/channel/distributed/controller/kafkasecretinjection/README.md
  pkg/channel/distributed/dispatcher/README.md
  pkg/channel/distributed/receiver/README.md
  pkg/source/README.md
Labels: approved, cla: yes, lgtm, size/XL

#121 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#123 Remove filterevents
  hack/tools.go
  vendor/knative.dev/eventing/test/test_images/filterevents/main.go
  vendor/knative.dev/eventing/test/test_images/filterevents/pod.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#125 Revert custom .ko.yaml back to eventing-contrib value.
  .ko.yaml
Labels: approved, cla: yes, lgtm, size/XS

#128 DeepCopy the entire set of conditions
  go.mod
  pkg/apis/sources/v1alpha1/kafka_conversion.go
  pkg/apis/sources/v1alpha1/kafka_types.go
  pkg/apis/sources/v1alpha1/roundtrip_test.go
  pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/sources/v1beta1/fuzzer.go
  pkg/apis/sources/v1beta1/roundtrip_test.go
  test/lib/listers.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/codec.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/compatibility.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/roundtrip.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/fuzzer/fuzzer.go
  vendor/knative.dev/pkg/apis/testing/roundtrip/roundtrip.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#139 populate newly required env vars in receiver/dispatcher
  pkg/channel/distributed/controller/constants/constants.go
  pkg/channel/distributed/controller/kafkachannel/dispatcher.go
  pkg/channel/distributed/controller/kafkasecret/receiver.go
  pkg/channel/distributed/controller/testing/data.go
Labels: approved, cla: yes, lgtm, size/M

#130 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/go.mod
  vendor/golang.org/x/oauth2/go.sum
  vendor/golang.org/x/tools/go/internal/gcimporter/gcimporter.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gocommand/version.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/google.golang.org/api/internal/creds.go
  vendor/google.golang.org/api/internal/impersonate/impersonate.go
  vendor/google.golang.org/api/internal/service-account.json
  vendor/google.golang.org/api/internal/settings.go
  vendor/google.golang.org/api/option/option.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/api/transport/grpc/dial.go
  vendor/google.golang.org/api/transport/http/dial.go
  vendor/google.golang.org/api/transport/internal/dca/dca.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_context.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_context.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_types.go
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_message_handler.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/inmemorychannel.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing_test_helper.go
  vendor/knative.dev/eventing/test/lib/k8s_events.go
  vendor/knative.dev/eventing/test/lib/operation.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/recordevents/observer/observer.go
  vendor/knative.dev/eventing/test/lib/recordevents/observer/reply.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/constructor.go
  vendor/knative.dev/eventing/test/lib/recordevents/resources.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/reconciler.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#141 Use the network.GetServiceHostname helper
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel_test.go
  pkg/channel/consolidated/reconciler/controller/resources/service.go
  pkg/channel/consolidated/reconciler/controller/resources/service_test.go
  pkg/channel/distributed/controller/kafkachannel/channel.go
Labels: approved, cla: yes, lgtm, size/S

#142 Update one remaining reference
  pkg/channel/distributed/controller/kafkachannel/channel.go
  vendor/knative.dev/eventing/pkg/reconciler/names/mtbroker.go
  vendor/knative.dev/eventing/pkg/reconciler/names/names.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#115 Updates
  go.mod
  go.sum
  pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/reconciler.go
  pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/kafkasource/reconciler.go
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/adapter/v2/config.go
  vendor/knative.dev/eventing/pkg/channel/history_transformer.go
  vendor/knative.dev/eventing/pkg/channel/message_receiver.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/reconciler/source/config_watcher.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_data_plane_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/traces.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/zipkin.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/uri.go
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/eventing/test/test_images/utils.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#109 use default autocommit configuration
  pkg/source/adapter/adapter.go
Labels: approved, cla: yes, lgtm, size/XS

#140 Add distributed trace headers
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/tracing.go
  pkg/channel/distributed/common/config/observability_test.go
  pkg/channel/distributed/common/metrics/stats_reporter_test.go
  pkg/channel/distributed/common/testing/util.go
  pkg/channel/distributed/controller/config/config.go
  pkg/channel/distributed/controller/kafkachannel/reconciler.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/handler.go
  pkg/channel/distributed/dispatcher/testing/mocks.go
  pkg/channel/distributed/receiver/producer/producer.go
  pkg/common/consumer/consumer_factory.go
  pkg/common/tracing/tracing.go
  pkg/common/tracing/tracing_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#144 Fix KafkaBinding conversion
  config/source/resources/kafkabinding.yaml
  pkg/apis/bindings/v1alpha1/kafka_conversion.go
  pkg/apis/bindings/v1alpha1/kafka_conversion_test.go
Labels: approved, cla: yes, lgtm, size/S

#129 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#147 add kafka binding fuzzer
  pkg/apis/bindings/v1alpha1/roundtrip_test.go
  pkg/apis/bindings/v1beta1/fuzzer.go
  pkg/apis/bindings/v1beta1/roundtrip_test.go
Labels: approved, cla: yes, lgtm, size/L

#149 Updates to latest
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/source/config_watcher.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#131 Allow using webhook configurations as a library
  cmd/webhook/main.go
  pkg/channel/consolidated/webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/L

#112 Adding KinD for e2e
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/L

#117 Allow registering custom conditions for different channel implementations
  pkg/apis/messaging/v1alpha1/kafka_channel_lifecycle.go
  pkg/apis/messaging/v1alpha1/kafka_channel_lifecycle_test.go
  pkg/apis/messaging/v1beta1/kafka_channel_lifecycle.go
  pkg/apis/messaging/v1beta1/kafka_channel_lifecycle_test.go
Labels: approved, cla: yes, lgtm, size/L

#150 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/ghutil/client.go
  vendor/knative.dev/pkg/test/mako/config/benchmark.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#151 Update to Strimzi 0.20
  test/config/100-kafka-ephemeral-triple-2.5.0.yaml
  test/config/100-kafka-ephemeral-triple-2.6.0.yaml
  test/config/100-strimzi-cluster-operator-0.20.0.yaml
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XXL

#153 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#156 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S
