Repository knative-extensions/eventing-kafka, pull requests merged in 2021-11, with the labels that each got.

#963 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#966 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#967 Fix post install jobs golang path
  config/channel/post-install/storage-version-migrator.yaml
  config/source/post-install/storage-version-migrator.yaml
Labels: cla: yes, size/XS, lgtm, approved

#968 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/S

#972 Pin sarama version to v1.29.1
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/L

#970 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, size/XS, lgtm, approved

#971 Extra CRD separation for source/binding
  config/source/common/resources/binding/kafkabinding.yaml
  config/source/common/resources/kafkabinding.yaml
  config/source/common/resources/kafkasource.yaml
  config/source/common/resources/source/kafkasource.yaml
  hack/release.sh
Labels: cla: yes, lgtm, approved, size/L

#974 Remove sleep and wait for KafkaSource reconciliation
  test/e2e/helpers/kafka_source_test_helper.go
  test/e2e/kafka_source_test.go
  test/lib/creation.go
Labels: cla: yes, lgtm, approved, size/M

#977 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#914 Reverting coc changes
  CODE-OF-CONDUCT.md
Labels: cla: yes, lgtm, approved, size/S

#978 Retry on Webhook EOF Errors
  test/lib/creation.go
Labels: cla: yes, lgtm, approved, size/M

#979 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, lgtm, approved, size/S

#982 [main] Update actions
  .github/workflows/knative-verify.yaml
Labels: cla: yes, size/XS, lgtm, approved

#981 fix vulnerable dependency packages
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#983 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/request.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#984 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/test/lib/duck/resource_getters.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/L

#985 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#965 Document maturity levels in sandbox
  README.md
Labels: cla: yes, size/XS, lgtm, approved

#987 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#991 Replace ghodss package with kubernetes-sigs for yaml
  go.mod
  go.sum
  pkg/common/client/config.go
  pkg/common/client/config_test.go
  pkg/common/client/yaml.go
  pkg/common/kafka/sarama/sarama.go
  third_party/VENDOR-LICENSE/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/modules.txt
Labels: cla: yes, size/XXL, lgtm, approved

#992 Fix version migration job pointing to the wrong CRD
  config/source/post-install/clusterrole.yaml
  config/source/post-install/storage-version-migrator.yaml
Labels: cla: yes, size/XS, lgtm, approved

#986 Wait for topic readiness after creation
  pkg/source/reconciler/source/kafkasource.go
  test/e2e/helpers/kafka_helper.go
Labels: cla: yes, lgtm, approved, size/M

#993 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/reconciler/filter.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/L

#994 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/XS, lgtm, approved

#996 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/conformance/helpers/broker_control_plane_test_helper.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#997 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/kmap/lookup.go
  vendor/knative.dev/pkg/kmap/map.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/L

#998 Add IsReady & Increase timeout to KafkaSource tests
  test/e2e/helpers/kafka_helper.go
  test/e2e/helpers/kafka_source_test_helper.go
Labels: cla: yes, size/XS, lgtm, approved

#999 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/utils/headers.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_test_helper.go
  vendor/knative.dev/eventing/test/lib/operation.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#1000 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/L

#1004 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, size/XS, lgtm, approved

#1002 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#1001 [KafkaChannels] Pass-through "additional headers"
  cmd/channel/distributed/receiver/main.go
  pkg/channel/consolidated/dispatcher/consumer_message_handler.go
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/handler.go
  pkg/channel/distributed/dispatcher/dispatcher/handler_test.go
  pkg/channel/distributed/receiver/producer/producer.go
  pkg/channel/distributed/receiver/producer/producer_test.go
  pkg/common/tracing/tracing.go
  pkg/common/tracing/tracing_test.go
Labels: cla: yes, lgtm, approved, size/L
