Repository knative-extensions/eventing-kafka, pull requests merged in 2021-05, with the labels that each got.

#597 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
Labels: approved, cla: yes, lgtm, size/S

#598 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/control-protocol/pkg/connection.go
  vendor/knative.dev/control-protocol/pkg/network/base_connection.go
  vendor/knative.dev/control-protocol/pkg/network/client_connection.go
  vendor/knative.dev/control-protocol/pkg/network/errors.go
  vendor/knative.dev/control-protocol/pkg/network/message_queue.go
  vendor/knative.dev/control-protocol/pkg/network/server_connection.go
  vendor/knative.dev/control-protocol/pkg/service/service.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#601 Attempt to fix the e2e tests
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/XS

#589 ResetOffset API & CRD
  config/command/resources/resetoffset-crd.yaml
  hack/update-codegen.sh
  pkg/apis/kafka/register.go
  pkg/apis/kafka/v1alpha1/doc.go
  pkg/apis/kafka/v1alpha1/register.go
  pkg/apis/kafka/v1alpha1/register_test.go
  pkg/apis/kafka/v1alpha1/reset_offset_defaults.go
  pkg/apis/kafka/v1alpha1/reset_offset_defaults_test.go
  pkg/apis/kafka/v1alpha1/reset_offset_lifecycle.go
  pkg/apis/kafka/v1alpha1/reset_offset_lifecycle_test.go
  pkg/apis/kafka/v1alpha1/reset_offset_types.go
  pkg/apis/kafka/v1alpha1/reset_offset_types_test.go
  pkg/apis/kafka/v1alpha1/reset_offset_validation.go
  pkg/apis/kafka/v1alpha1/reset_offset_validation_test.go
  pkg/apis/kafka/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/kafka/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/kafka/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/kafka/v1alpha1/fake/fake_kafka_client.go
  pkg/client/clientset/versioned/typed/kafka/v1alpha1/fake/fake_resetoffset.go
  pkg/client/clientset/versioned/typed/kafka/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kafka/v1alpha1/kafka_client.go
  pkg/client/clientset/versioned/typed/kafka/v1alpha1/resetoffset.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/kafka/interface.go
  pkg/client/informers/externalversions/kafka/v1alpha1/interface.go
  pkg/client/informers/externalversions/kafka/v1alpha1/resetoffset.go
  pkg/client/injection/informers/kafka/v1alpha1/resetoffset/fake/fake.go
  pkg/client/injection/informers/kafka/v1alpha1/resetoffset/filtered/fake/fake.go
  pkg/client/injection/informers/kafka/v1alpha1/resetoffset/filtered/resetoffset.go
  pkg/client/injection/informers/kafka/v1alpha1/resetoffset/resetoffset.go
  pkg/client/injection/reconciler/kafka/v1alpha1/resetoffset/controller.go
  pkg/client/injection/reconciler/kafka/v1alpha1/resetoffset/reconciler.go
  pkg/client/injection/reconciler/kafka/v1alpha1/resetoffset/state.go
  pkg/client/listers/kafka/v1alpha1/expansion_generated.go
  pkg/client/listers/kafka/v1alpha1/resetoffset.go
Labels: approved, cla: yes, size/XXL

#600 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#599 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#609 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#603 [distributed kafkachannel] Refactor remove secret watcher
  cmd/channel/distributed/controller/main.go
  config/channel/distributed/300-kafka-secret.yaml
  config/channel/distributed/README.md
  docs/kind_kafka_cluster.md
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/distributed/common/config/secretwatcher_test.go
  pkg/channel/distributed/common/kafka/README.md
  pkg/channel/distributed/common/kafka/constants/constants.go
  pkg/channel/distributed/common/kafka/sarama/sarama.go
  pkg/channel/distributed/common/kafka/sarama/sarama_test.go
  pkg/channel/distributed/controller/README.md
  pkg/channel/distributed/controller/constants/constants.go
  pkg/channel/distributed/controller/kafkachannel/channel.go
  pkg/channel/distributed/controller/kafkachannel/controller.go
  pkg/channel/distributed/controller/kafkachannel/dispatcher.go
  pkg/channel/distributed/controller/kafkachannel/kafkachannel.go
  pkg/channel/distributed/controller/kafkachannel/receiver.go
  pkg/channel/distributed/controller/kafkachannel/reconciler.go
  pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
  pkg/channel/distributed/controller/kafkasecret/controller.go
  pkg/channel/distributed/controller/kafkasecret/controller_test.go
  pkg/channel/distributed/controller/kafkasecret/kafkachannel.go
  pkg/channel/distributed/controller/kafkasecret/reconciler.go
  pkg/channel/distributed/controller/kafkasecret/reconciler_test.go
  pkg/channel/distributed/controller/kafkasecretinformer/fake/fake.go
  pkg/channel/distributed/controller/kafkasecretinformer/kafkasecretinformer.go
  pkg/channel/distributed/controller/kafkasecretinformer/kafkasecretinformer_test.go
  pkg/channel/distributed/controller/kafkasecretinjection/README.md
  pkg/channel/distributed/controller/kafkasecretinjection/controller.go
  pkg/channel/distributed/controller/kafkasecretinjection/reconciler.go
  pkg/channel/distributed/controller/kafkasecretinjection/state.go
  pkg/channel/distributed/controller/testing/data.go
  pkg/channel/distributed/controller/util/channel.go
  pkg/channel/distributed/controller/util/channel_test.go
  pkg/channel/distributed/controller/util/secret.go
  pkg/channel/distributed/controller/util/secret_test.go
  pkg/channel/distributed/receiver/README.md
  pkg/common/config/eventingkafkaconfig.go
  pkg/common/config/testing/util.go
  pkg/common/constants/constants.go
  pkg/common/testing/constants.go
  pkg/common/testing/util.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#616 Update deps
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_chain_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_dls_test_helper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#617 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#615 post-install script to migrate KafkaSource to v1beta1
  config/post-install/clusterrole.yaml
  config/post-install/placeholder.go
  config/post-install/serviceaccount.yaml
  config/post-install/storage-version-migrator.yaml
Labels: approved, cla: yes, lgtm, size/L

#587 [scheduler, mtsource] Initial HA support for MT Kafka source
  config/source/multi/500-controller-service.yaml
  config/source/multi/deployments/adapter.yaml
  config/source/multi/deployments/controller.yaml
  config/source/multi/roles/clusterrole.yaml
  pkg/apis/duck/v1alpha1/placement_types.go
  pkg/common/scheduler/statefulset/autoscaler.go
  pkg/common/scheduler/statefulset/autoscaler_test.go
  pkg/common/scheduler/statefulset/scheduler.go
  pkg/common/scheduler/statefulset/scheduler_test.go
  pkg/common/scheduler/statefulset/state.go
  pkg/common/scheduler/statefulset/state_test.go
  pkg/source/reconciler/mtsource/controller.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/node/node.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#621 [mtsource] Fix crash when secret is missing
  pkg/source/mtadapter/adapter.go
  pkg/source/mtadapter/adapter_test.go
  pkg/source/mtadapter/controller.go
  pkg/source/mtadapter/kafkasource.go
Labels: cla: yes, lgtm, size/L

#620 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/S

#610 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/adapter/v2/test/test_client.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#625 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/upgrade/prober/forwarder.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#604 [source] fix issue with offset not being initialized before session is closed
  pkg/source/adapter/adapter.go
  pkg/source/adapter/adapter_test.go
Labels: approved, cla: yes, lgtm, size/L

#638 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/L

#641 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/adapter/v2/test/test_client.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_event_tranformation_test_helper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#640 start to remove vreplicas from biggest ordinal
  pkg/common/scheduler/statefulset/scheduler.go
  pkg/common/scheduler/statefulset/scheduler_test.go
Labels: approved, cla: yes, lgtm, size/S

#642 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/resources/eventing.go
  vendor/knative.dev/eventing/test/upgrade/prober/config.toml
  vendor/knative.dev/eventing/test/upgrade/prober/configuration.go
  vendor/knative.dev/eventing/test/upgrade/prober/continual.go
  vendor/knative.dev/eventing/test/upgrade/prober/errors.go
  vendor/knative.dev/eventing/test/upgrade/prober/forwarder.go
  vendor/knative.dev/eventing/test/upgrade/prober/prober.go
  vendor/knative.dev/eventing/test/upgrade/prober/receiver.go
  vendor/knative.dev/eventing/test/upgrade/prober/sender.go
  vendor/knative.dev/eventing/test/upgrade/prober/sut/broker.go
  vendor/knative.dev/eventing/test/upgrade/prober/sut/default.go
  vendor/knative.dev/eventing/test/upgrade/prober/sut/types.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/config/defaults.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/event/types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#618 [mtsource] wait for stadapter to stop before starting the new one
  pkg/common/consumer/consumer_factory.go
  pkg/source/mtadapter/adapter.go
  pkg/source/mtadapter/adapter_test.go
Labels: cla: yes, lgtm, size/M

#648 Fix linter error
  pkg/source/mtadapter/adapter_test.go
Labels: approved, cla: yes, lgtm, size/XS

#644 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#650 Remove post install script
  config/post-install/clusterrole.yaml
  config/post-install/placeholder.go
  config/post-install/serviceaccount.yaml
  config/post-install/storage-version-migrator.yaml
Labels: approved, cla: yes, lgtm, size/L

#563 [QE] Continual tests for KafkaSource for upgrade testing
  test/test_images/wathola-kafka-sender/main.go
  test/test_images/wathola-kafka-sender/pod.yaml
  test/upgrade/config.toml
  test/upgrade/continual.go
  test/upgrade/continual/channel-config.toml
  test/upgrade/continual/channel.go
  test/upgrade/continual/kafkasender.go
  test/upgrade/continual/source-config.toml
  test/upgrade/continual/source.go
  test/upgrade/continual/types.go
  test/upgrade/continual/verification.go
  test/upgrade/suite.go
Labels: approved, cla: yes, lgtm, size/XL

#574 Copy OWNERS_ALIASES from knative/community; fill in OWNERS files
  OWNERS
  cmd/source/mtcontroller/OWNERS
  cmd/source/mtreceive_adapter/OWNERS
  config/source/multi/OWNERS
  hack/OWNERS
  pkg/common/scheduler/OWNERS
  pkg/source/OWNERS
  test/OWNERS
Labels: cla: yes, lgtm, size/M

#654 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#652 pod name ordinal can have multiple digits
  pkg/common/scheduler/statefulset/scheduler.go
Labels: approved, cla: yes, lgtm, size/XS

#653 Remove CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/S

#622 Consolidate configmap
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  config/channel/consolidated/configmaps/kafka-config.yaml
  config/channel/distributed/300-eventing-kafka-configmap.yaml
  config/channel/distributed/README.md
  pkg/channel/consolidated/README.md
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
  pkg/channel/consolidated/dispatcher/dispatcher_test.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel_test.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
  pkg/channel/consolidated/utils/util.go
  pkg/channel/consolidated/utils/util_test.go
  pkg/channel/distributed/common/config/secretwatcher.go
  pkg/channel/distributed/common/config/secretwatcher_test.go
  pkg/channel/distributed/common/env/constants.go
  pkg/channel/distributed/common/kafka/constants/constants.go
  pkg/channel/distributed/common/kafka/sarama/sarama.go
  pkg/channel/distributed/common/kafka/sarama/sarama_test.go
  pkg/channel/distributed/controller/config/config.go
  pkg/channel/distributed/controller/config/config_test.go
  pkg/channel/distributed/controller/constants/constants.go
  pkg/channel/distributed/controller/kafkachannel/controller.go
  pkg/channel/distributed/controller/kafkachannel/controller_test.go
  pkg/channel/distributed/controller/kafkachannel/dispatcher.go
  pkg/channel/distributed/controller/kafkachannel/receiver.go
  pkg/channel/distributed/controller/kafkachannel/reconciler.go
  pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
  pkg/channel/distributed/controller/kafkachannel/topic.go
  pkg/channel/distributed/controller/kafkachannel/topic_test.go
  pkg/channel/distributed/controller/testing/data.go
  pkg/channel/distributed/controller/util/channel.go
  pkg/channel/distributed/controller/util/channel_test.go
  pkg/channel/distributed/controller/util/compare_test.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/handler.go
  pkg/channel/distributed/receiver/producer/producer.go
  pkg/common/client/admin_client.go
  pkg/common/client/config_test.go
  pkg/common/config/eventingkafkaconfig.go
  pkg/common/config/kafkaconfigmapwatcher_test.go
  pkg/common/config/testing/util.go
  pkg/common/config/util.go
  pkg/common/config/util_test.go
  pkg/common/constants/constants.go
  pkg/common/kafka/sarama/sarama.go
  pkg/common/kafka/sarama/sarama_test.go
  pkg/common/testing/constants.go
  pkg/common/testing/util.go
  pkg/source/client/client_test.go
  test/config/config-kafka-sasl.yaml
  test/config/config-kafka-tls.yaml
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#658 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/condition_types.go
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/duck/register.go
  vendor/knative.dev/pkg/apis/duck/v1/register.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/register.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/register.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/system/env.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#661 [v0.21] Cancel dispatching messages when consumer group session is closed
  pkg/common/consumer/consumer_handler.go
Labels: approved, cla: yes, lgtm, size/M

#660 Receiver liveness before sarama calls
  cmd/channel/distributed/receiver/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#659 Make sure ConsumeClaim exit before rebalance.timeout
  pkg/common/consumer/consumer_handler.go
Labels: approved, cla: yes, lgtm, size/M

#626 Resetoffset controller
  go.mod
  pkg/apis/kafka/v1alpha1/reset_offset_lifecycle.go
  pkg/apis/kafka/v1alpha1/reset_offset_lifecycle_test.go
  pkg/channel/distributed/common/kafka/util/util.go
  pkg/channel/distributed/common/kafka/util/util_test.go
  pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
  pkg/channel/distributed/controller/util/channel_test.go
  pkg/channel/distributed/controller/util/subscription.go
  pkg/channel/distributed/controller/util/subscription_test.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/common/commands/resetoffset/controller/controller.go
  pkg/common/commands/resetoffset/controller/controller_test.go
  pkg/common/commands/resetoffset/controller/event.go
  pkg/common/commands/resetoffset/controller/event_test.go
  pkg/common/commands/resetoffset/controller/offsets.go
  pkg/common/commands/resetoffset/controller/offsets_test.go
  pkg/common/commands/resetoffset/controller/reconciler.go
  pkg/common/commands/resetoffset/controller/reconciler_test.go
  pkg/common/commands/resetoffset/controller/testing/data.go
  pkg/common/commands/resetoffset/controller/testing/factory.go
  pkg/common/commands/resetoffset/controller/testing/lister.go
  pkg/common/commands/resetoffset/controller/testing/mock.go
  pkg/common/commands/resetoffset/refmappers/subscription.go
  pkg/common/commands/resetoffset/refmappers/subscription_test.go
  pkg/common/commands/resetoffset/refmappers/testing/mocks.go
  pkg/common/commands/resetoffset/refmappers/types.go
  third_party/VENDOR-LICENSE/github.com/stretchr/objx/LICENSE
  vendor/knative.dev/eventing/pkg/client/injection/informers/factory/fake/fake.go
  vendor/knative.dev/eventing/pkg/client/injection/informers/messaging/v1/subscription/fake/fake.go
  vendor/knative.dev/eventing/pkg/client/injection/informers/messaging/v1/subscription/subscription.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#672 [release-0.23] Make sure ConsumeClaim exit before rebalance.timeout (#659)
  pkg/common/consumer/consumer_handler.go
Labels: approved, cla: yes, lgtm, size/M

#627 Updating to latest of Strimzi 0.23, with its v1beta2 APIs
  .wokeignore
  test/config/100-kafka-ephemeral-triple-2.8.0.yaml
  test/config/100-strimzi-cluster-operator-0.20.0.yaml
  test/config/100-strimzi-cluster-operator-0.23.0.yaml
  test/config/100-strimzi-users-0.23.0.yaml
  test/e2e-common.sh
  test/e2e/helpers/kafka_helper.go
  test/rekt/resources/kafkatopic/topic.go
  test/rekt/resources/kafkatopic/topic.yaml
  test/rekt/resources/kafkatopic/topic_test.go
Labels: approved, cla: yes, lgtm, size/XXL
