Repository knative-extensions/eventing-kafka, pull requests merged in 2021-10, with the labels that each got.

#886 [0.24] KafkaChannel to init offsets before dispatcher
  go.mod
  go.sum
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
  pkg/channel/consolidated/dispatcher/dispatcher_test.go
  pkg/channel/consolidated/dispatcher/subscription_endpoint.go
  pkg/channel/consolidated/dispatcher/subscription_endpoint_test.go
  pkg/channel/consolidated/reconciler/controller/controller.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel_test.go
  pkg/channel/consolidated/reconciler/controller/lister.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
  pkg/channel/consolidated/status/status.go
  pkg/channel/consolidated/status/status_test.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel_test.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
  pkg/common/consumer/consumer_factory.go
  pkg/common/consumer/consumer_factory_test.go
  pkg/common/consumer/consumer_manager.go
  pkg/common/consumer/consumer_manager_test.go
  pkg/common/consumer/consumergroup_offsets_checker.go
  pkg/common/consumer/testing/mocks.go
  pkg/common/kafka/offset/offsets.go
  pkg/common/kafka/offset/offsets_test.go
  pkg/common/testing/mocks.go
  pkg/source/adapter/adapter.go
  third_party/VENDOR-LICENSE/knative.dev/networking/pkg/prober/LICENSE
  vendor/knative.dev/networking/LICENSE
  vendor/knative.dev/networking/pkg/prober/doc.go
  vendor/knative.dev/networking/pkg/prober/prober.go
  vendor/modules.txt
Labels: cla: yes, size/XXL, lgtm, approved

#908 Adding finalizers and status subresources for KafkaChannel storage version migrator
  config/channel/post-install/clusterrole.yaml
Labels: cla: yes, size/XS, lgtm, approved

#913 [0.25] KafkaChannel to init offsets before dispatcher
  go.mod
  go.sum
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
  pkg/channel/consolidated/dispatcher/dispatcher_test.go
  pkg/channel/consolidated/dispatcher/subscription_endpoint.go
  pkg/channel/consolidated/dispatcher/subscription_endpoint_test.go
  pkg/channel/consolidated/reconciler/controller/controller.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel_test.go
  pkg/channel/consolidated/reconciler/controller/lister.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
  pkg/channel/consolidated/status/status.go
  pkg/channel/consolidated/status/status_test.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel_test.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
  pkg/common/consumer/consumer_factory.go
  pkg/common/consumer/consumer_factory_test.go
  pkg/common/consumer/consumer_manager.go
  pkg/common/consumer/consumer_manager_test.go
  pkg/common/consumer/consumergroup_offsets_checker.go
  pkg/common/consumer/testing/mocks.go
  pkg/common/kafka/offset/offsets.go
  pkg/common/kafka/offset/offsets_test.go
  pkg/common/testing/mocks.go
  pkg/source/adapter/adapter.go
  third_party/VENDOR-LICENSE/knative.dev/networking/pkg/prober/LICENSE
  vendor/knative.dev/networking/LICENSE
  vendor/knative.dev/networking/pkg/prober/doc.go
  vendor/knative.dev/networking/pkg/prober/prober.go
  vendor/modules.txt
Labels: cla: yes, size/XXL, lgtm, approved

#871 delete consumer group when deleting source
  pkg/source/mtadapter/adapter.go
  pkg/source/mtadapter/adapter_test.go
  pkg/source/mtadapter/controller.go
  pkg/source/mtadapter/kafkasource.go
  pkg/source/reconciler/common/finalizer.go
  pkg/source/reconciler/common/finalizer_test.go
  pkg/source/reconciler/mtsource/controller.go
  pkg/source/reconciler/mtsource/kafkasource.go
  pkg/source/reconciler/source/kafkasource.go
  test/e2e-common.sh
Labels: cla: yes, lgtm, approved, size/L

#888 README for new MT Scheduler with pluggable policies
  pkg/common/scheduler/README.md
Labels: cla: yes, lgtm, approved, size/L

#919 [trivial] Add test directory to ignored codecov directory
  .codecov.yaml
Labels: cla: yes, size/XS, lgtm, approved

#924 [0.24] KafkaChannel dispatcher offset checking improvements
  cmd/channel/distributed/dispatcher/main.go
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
  pkg/channel/consolidated/dispatcher/dispatcher_test.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel_test.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
  pkg/common/consumer/consumer_factory.go
  pkg/common/consumer/consumer_factory_test.go
  pkg/common/consumer/consumer_handler.go
  pkg/common/consumer/consumer_manager.go
  pkg/common/consumer/consumer_manager_test.go
  pkg/common/consumer/consumergroup_offsets_checker.go
  pkg/common/consumer/testing/mocks.go
  pkg/source/adapter/adapter.go
Labels: cla: yes, lgtm, approved, size/L

#929 [0.25] KafkaChannel dispatcher offset checking improvements
  cmd/channel/distributed/dispatcher/main.go
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
  pkg/channel/consolidated/dispatcher/dispatcher_test.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel_test.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
  pkg/common/consumer/consumer_factory.go
  pkg/common/consumer/consumer_factory_test.go
  pkg/common/consumer/consumer_handler.go
  pkg/common/consumer/consumer_manager.go
  pkg/common/consumer/consumer_manager_test.go
  pkg/common/consumer/consumergroup_offsets_checker.go
  pkg/common/consumer/testing/mocks.go
  pkg/source/adapter/adapter.go
Labels: cla: yes, lgtm, approved, size/L

#911 [main] KafkaChannel to init offsets before dispatcher
  cmd/channel/distributed/dispatcher/main.go
  go.mod
  go.sum
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
  pkg/channel/consolidated/dispatcher/dispatcher_test.go
  pkg/channel/consolidated/dispatcher/subscription_endpoint.go
  pkg/channel/consolidated/dispatcher/subscription_endpoint_test.go
  pkg/channel/consolidated/reconciler/controller/controller.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel_test.go
  pkg/channel/consolidated/reconciler/controller/lister.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
  pkg/channel/consolidated/status/status.go
  pkg/channel/consolidated/status/status_test.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel_test.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
  pkg/common/consumer/consumer_factory.go
  pkg/common/consumer/consumer_factory_test.go
  pkg/common/consumer/consumer_handler.go
  pkg/common/consumer/consumer_manager.go
  pkg/common/consumer/consumer_manager_test.go
  pkg/common/consumer/consumergroup_offsets_checker.go
  pkg/common/consumer/testing/mocks.go
  pkg/common/kafka/offset/offsets.go
  pkg/common/kafka/offset/offsets_test.go
  pkg/common/testing/mocks.go
  pkg/source/adapter/adapter.go
  third_party/VENDOR-LICENSE/knative.dev/networking/pkg/prober/LICENSE
  vendor/knative.dev/networking/LICENSE
  vendor/knative.dev/networking/pkg/prober/doc.go
  vendor/knative.dev/networking/pkg/prober/prober.go
  vendor/modules.txt
Labels: cla: yes, size/XXL, lgtm, approved

#909 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/eventing/pkg/channel/message_dispatcher.go
  vendor/knative.dev/eventing/test/lib/recordevents/receiver/receiver.go
  vendor/knative.dev/eventing/test/lib/recordevents/resources.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/L

#935 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: cla: yes, size/XS, lgtm, approved

#937 Add linters that are used in eventing
  .golangci.yaml
  pkg/channel/consolidated/reconciler/controller/controller.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/distributed/controller/kafkachannel/controller.go
  pkg/common/scheduler/statefulset/scheduler.go
  test/e2e/helpers/kafka_source_test_helper.go
Labels: cla: yes, lgtm, approved, size/M

#943 Default KafkaSource sink ref namespace to object namespace
  pkg/apis/sources/v1beta1/kafka_defaults.go
  pkg/apis/sources/v1beta1/kafka_defaults_test.go
Labels: cla: yes, lgtm, approved, size/M
