Repository knative-extensions/eventing-kafka, pull requests merged in 2021-08, with the labels that each got.

#784 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/reconciler.go
  pkg/client/injection/reconciler/kafka/v1alpha1/resetoffset/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/kafkasource/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#785 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/recordevents/resources.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#787 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, size/XS, lgtm, approved

#790 Upgrade KafkaCat image used in KafkaSource e2e tests
  test/e2e/helpers/kafka_helper.go
Labels: cla: yes, size/XS, lgtm, approved

#796 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/upgrade/prober/prober.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#791 Cleanup rekt tests.
  test/rekt/features/kafkasource/data_plane.go
  test/rekt/features/kafkasource/mt_data_plane.go
  test/rekt/features/kafkasource/readiness.go
  test/rekt/features/kafkatopic/readiness.go
  test/rekt/resources/kafkacat/kafkacat.go
  test/rekt/resources/kafkacat/kafkacat_test.go
  test/rekt/resources/kafkachannel/kafkachannel.go
  test/rekt/resources/kafkachannel/kafkachannel_test.go
  test/rekt/resources/kafkasource/kafkasource.go
  test/rekt/resources/kafkasource/kafkasource_test.go
  test/rekt/resources/kafkatopic/topic.go
  test/rekt/resources/kafkatopic/topic_test.go
  test/rekt/resources/resetoffset/resetoffset.go
  test/rekt/resources/resetoffset/resetoffset_test.go
Labels: cla: yes, lgtm, approved, size/L

#795 fix-reconfigure-and-reconciliation-issues
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  pkg/channel/distributed/common/kafka/util/util.go
  pkg/channel/distributed/common/kafka/util/util_test.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel_test.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
  pkg/common/consumer/consumer_manager.go
  pkg/common/consumer/consumer_manager_test.go
  pkg/common/consumer/testing/mocks.go
Labels: cla: yes, lgtm, approved, size/L

#797 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/channel/message_receiver.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#799 Separate CRDs, like we have on eventing core
  hack/release.sh
Labels: cla: yes, size/XS, lgtm, approved

#800 Address TODO from releases 0.22 and 0.23
  pkg/apis/messaging/v1beta1/kafka_channel_defaults.go
Labels: cla: yes, lgtm, approved, size/S

#801 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#798 [Consolidated KafkaChannel] Set KafkaChannel consolidated dispatcher OwenrRef
  config/channel/consolidated/500-dispatcher.yaml
  config/channel/consolidated/deployments/controller.yaml
  config/channel/consolidated/deployments/dispatcher.yaml
  pkg/channel/consolidated/reconciler/controller/controller.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel_test.go
  pkg/channel/consolidated/reconciler/controller/resources/dispatcher.go
  pkg/channel/consolidated/reconciler/controller/resources/dispatcher_service_test.go
  pkg/channel/consolidated/reconciler/controller/resources/dispatcher_test.go
  pkg/channel/consolidated/reconciler/controller/resources/role_binding_test.go
  pkg/channel/consolidated/reconciler/controller/resources/service_account_test.go
  pkg/channel/consolidated/reconciler/controller/resources/service_test.go
Labels: cla: yes, lgtm, approved, size/XL

#803 [release-0.23] [Consolidated KafkaChannel] Set KafkaChannel consolidated dispatcher OwenrRef
  config/channel/consolidated/500-dispatcher.yaml
  config/channel/consolidated/deployments/controller.yaml
  config/channel/consolidated/deployments/dispatcher.yaml
  pkg/channel/consolidated/reconciler/controller/controller.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel_test.go
  pkg/channel/consolidated/reconciler/controller/resources/dispatcher.go
  pkg/channel/consolidated/reconciler/controller/resources/dispatcher_service_test.go
  pkg/channel/consolidated/reconciler/controller/resources/dispatcher_test.go
  pkg/channel/consolidated/reconciler/controller/resources/role_binding_test.go
  pkg/channel/consolidated/reconciler/controller/resources/service_account_test.go
  pkg/channel/consolidated/reconciler/controller/resources/service_test.go
Labels: cla: yes, lgtm, approved, size/XL

#779 add initial offset to kafka source spec
  pkg/apis/sources/v1beta1/kafka_defaults.go
  pkg/apis/sources/v1beta1/kafka_defaults_test.go
  pkg/apis/sources/v1beta1/kafka_types.go
  pkg/apis/sources/v1beta1/kafka_validation.go
  pkg/apis/sources/v1beta1/kafka_validation_test.go
  pkg/common/client/config.go
  pkg/common/client/config_test.go
  pkg/source/client/client.go
  pkg/source/client/client_test.go
  pkg/source/reconciler/source/resources/receive_adapter.go
  pkg/source/reconciler/source/resources/receive_adapter_test.go
Labels: cla: yes, lgtm, approved, size/L

#809 removing confusing error message
  pkg/source/mtadapter/controller.go
  pkg/source/mtadapter/kafkasource.go
Labels: cla: yes, lgtm, approved, size/S

#808 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  pkg/client/injection/informers/bindings/v1beta1/kafkabinding/filtered/kafkabinding.go
  pkg/client/injection/informers/bindings/v1beta1/kafkabinding/kafkabinding.go
  pkg/client/injection/informers/kafka/v1alpha1/resetoffset/filtered/resetoffset.go
  pkg/client/injection/informers/kafka/v1alpha1/resetoffset/resetoffset.go
  pkg/client/injection/informers/messaging/v1beta1/kafkachannel/filtered/kafkachannel.go
  pkg/client/injection/informers/messaging/v1beta1/kafkachannel/kafkachannel.go
  pkg/client/injection/informers/sources/v1beta1/kafkasource/filtered/kafkasource.go
  pkg/client/injection/informers/sources/v1beta1/kafkasource/kafkasource.go
  vendor/knative.dev/eventing/pkg/client/injection/client/client.go
  vendor/knative.dev/eventing/pkg/client/injection/informers/eventing/v1/broker/broker.go
  vendor/knative.dev/eventing/pkg/client/injection/informers/messaging/v1/subscription/subscription.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/interfaces.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/apiextensions/v1/customresourcedefinition/customresourcedefinition.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/deployment.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/statefulset/statefulset.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/statefulset/statefulset_expansion.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/endpoints.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/namespace/namespace.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/node/node.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/service.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/serviceaccount/serviceaccount.go
  vendor/knative.dev/pkg/client/injection/kube/informers/rbac/v1/rolebinding/rolebinding.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, size/XXL, lgtm, approved

#806 Custom annotations labels
  config/channel/distributed/README.md
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel_test.go
  pkg/channel/consolidated/reconciler/controller/resources/dispatcher.go
  pkg/channel/consolidated/reconciler/controller/resources/dispatcher_service.go
  pkg/channel/consolidated/reconciler/testing/factory.go
  pkg/channel/distributed/controller/kafkachannel/dispatcher.go
  pkg/channel/distributed/controller/kafkachannel/receiver.go
  pkg/channel/distributed/controller/testing/data.go
  pkg/channel/distributed/controller/util/compare.go
  pkg/channel/distributed/controller/util/compare_test.go
  pkg/common/config/eventingkafkaconfig.go
  pkg/common/config/util.go
  pkg/common/config/util_test.go
  pkg/common/consumer/consumer_manager_test.go
Labels: cla: yes, lgtm, approved, size/XL

#805 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/S

#812 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, size/XS, lgtm, approved

#824 Remove a bit of copy-paste from the upstream channel
  pkg/apis/messaging/v1beta1/kafka_channel_defaults.go
  pkg/apis/messaging/v1beta1/kafka_channel_lifecycle.go
  pkg/apis/messaging/v1beta1/kafka_channel_types.go
  pkg/apis/messaging/v1beta1/kafka_channel_types_test.go
  pkg/apis/messaging/v1beta1/kafka_channel_validation.go
Labels: cla: yes, lgtm, approved, size/L

#830 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#831 Use `controller.Impl` tracker and cleanups
  cmd/channel/distributed/dispatcher/main.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel_test.go
  pkg/source/reconciler/binding/controller.go
  pkg/source/reconciler/mtsource/controller.go
  pkg/source/reconciler/source/controller.go
Labels: cla: yes, lgtm, approved, size/S, kind/cleanup

#828 Add retention time to kafkachannel crd
  config/channel/consolidated/configmaps/kafka-config.yaml
  config/channel/distributed/300-eventing-kafka-configmap.yaml
  config/channel/resources/kafkachannel-crd.yaml
  go.mod
  pkg/apis/kafka/v1alpha1/reset_offset_types.go
  pkg/apis/messaging/v1beta1/kafka_channel_defaults.go
  pkg/apis/messaging/v1beta1/kafka_channel_defaults_test.go
  pkg/apis/messaging/v1beta1/kafka_channel_types.go
  pkg/apis/messaging/v1beta1/kafka_channel_types_test.go
  pkg/apis/messaging/v1beta1/kafka_channel_validation.go
  pkg/apis/messaging/v1beta1/kafka_channel_validation_test.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/utils/util.go
  pkg/channel/consolidated/utils/util_test.go
  pkg/channel/distributed/controller/config/config.go
  pkg/channel/distributed/controller/config/config_test.go
  pkg/channel/distributed/controller/kafkachannel/topic.go
  pkg/channel/distributed/controller/kafkachannel/topic_test.go
  pkg/channel/distributed/controller/testing/data.go
  pkg/common/config/eventingkafkaconfig.go
  pkg/common/config/util.go
  pkg/common/config/util_test.go
  pkg/common/constants/constants.go
  pkg/common/kafka/sarama/sarama.go
  pkg/common/kafka/sarama/sarama_test.go
  pkg/common/testing/constants.go
  test/rekt/features/kafkachannel/util.go
  test/rekt/resources/kafkachannel/kafkachannel.go
  test/rekt/resources/kafkachannel/kafkachannel_test.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/XL

#832 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#843 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#811 KafkaSource supports ceOverrides
  pkg/source/adapter/adapter.go
  pkg/source/adapter/message.go
  pkg/source/mtadapter/adapter.go
  pkg/source/reconciler/source/resources/receive_adapter.go
  test/e2e/kafka_source.go
  test/lib/resources/kafka.go
  test/rekt/features/kafkasource/data_plane.go
  test/rekt/resources/kafkasource/kafkasource.go
  test/rekt/resources/kafkasource/kafkasource.yaml
  test/rekt/resources/kafkasource/kafkasource_test.go
Labels: cla: yes, lgtm, approved, size/L
