Repository knative-extensions/eventing-kafka, pull requests merged in 2021-06, with the labels that each got.

#674 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#668 Adjust MaxResponseSize based on the number of active stadapters
  config/source/multi/deployments/adapter.yaml
  config/source/multi/deployments/controller.yaml
  pkg/source/mtadapter/adapter.go
  pkg/source/mtadapter/adapter_test.go
Labels: approved, cla: yes, lgtm, size/L

#678 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#670 Bump go to 1.16
  .github/workflows/kind-e2e.yaml
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/XS

#677 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/channel/message_dispatcher.go
  vendor/knative.dev/eventing/test/upgrade/prober/sut/broker.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/config.go
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/apiextensions/v1/customresourcedefinition/customresourcedefinition.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/factory/factory.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/addressable/addressable.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/podspecable/podspecable.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/deployment.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/statefulset/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/statefulset/statefulset.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/endpoints.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/namespace/namespace.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/node/node.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/service.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/serviceaccount/serviceaccount.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/factory.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/rbac/v1/rolebinding/rolebinding.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/environment/config.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/knative.dev/reconciler-test/pkg/manifest/templates.go
  vendor/knative.dev/reconciler-test/resources/svc/service.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#673 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#681 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/errors.go
  vendor/github.com/evanphx/json-patch/v5/go.mod
  vendor/github.com/evanphx/json-patch/v5/go.sum
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/go.uber.org/zap/.travis.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/CONTRIBUTING.md
  vendor/go.uber.org/zap/FAQ.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/http_handler.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/write_syncer.go
  vendor/gopkg.in/evanphx/json-patch.v4/.travis.yml
  vendor/gopkg.in/evanphx/json-patch.v4/README.md
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#682 [mtsource] MaxResponseSize considers the number of connected brokers
  pkg/source/mtadapter/adapter.go
  pkg/source/mtadapter/adapter_test.go
Labels: approved, cla: yes, lgtm, size/S

#684 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/manifest/templates.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#680 Allow consolidated channel to use distributed-style secret format
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
  pkg/channel/consolidated/utils/util.go
  pkg/channel/consolidated/utils/util_test.go
  pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
  pkg/common/config/util.go
  pkg/common/config/util_test.go
  pkg/common/kafka/sarama/sarama.go
  pkg/common/kafka/sarama/sarama_test.go
Labels: approved, cla: yes, lgtm, size/L

#686 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/control-protocol/pkg/network/tls.go
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#687 Update Knative dependency for release-0.23
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/adapter/v2/test/test_client.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#690 Adding latest eventing deps
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_message_handler.go
  vendor/knative.dev/eventing/pkg/channel/stats_reporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#611 [Automated] Format markdown
  config/channel/distributed/README.md
  docs/kind_kafka_cluster.md
  pkg/channel/distributed/common/kafka/README.md
  pkg/channel/distributed/controller/README.md
  pkg/channel/distributed/receiver/README.md
Labels: approved, cla: yes, lgtm, size/M

#666 KafkaSource retries on error
  pkg/source/adapter/adapter.go
Labels: approved, cla: yes, lgtm, size/S

#693 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: approved, cla: yes, lgtm, size/M

#692 Update to latest eventing deps
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_message_handler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#695 Only run InitOffset once after the adapter has started
  pkg/source/adapter/adapter.go
Labels: approved, cla: yes, lgtm, size/S

#694 Revert to setting consumer.fetch options instead of MaxReponseSize
  config/source/multi/deployments/adapter.yaml
  pkg/source/mtadapter/adapter.go
  pkg/source/mtadapter/adapter_test.go
Labels: approved, cla: yes, lgtm, size/L

#688 Support eventing metrics
  pkg/channel/consolidated/dispatcher/consumer_message_handler.go
  pkg/channel/consolidated/dispatcher/dispatcher.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#698 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/control-protocol/pkg/service/service.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/scheme/scheme.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/factory.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_single_event_helper.go
  vendor/knative.dev/eventing/test/rekt/resources/svc/service.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#700 Remove creation of new dispatcher when secret changes
  cmd/channel/distributed/dispatcher/main.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel_test.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
  pkg/channel/distributed/receiver/producer/producer.go
  pkg/channel/distributed/receiver/producer/producer_test.go
  pkg/common/config/testing/util.go
Labels: approved, cla: yes, lgtm, size/L

#696 do not print out users' apikey
  pkg/common/client/config.go
Labels: approved, cla: yes, lgtm, size/XS

#561 [distributed kafkachannel] Distributed Dispatcher with common/consumer
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
  pkg/channel/distributed/dispatcher/dispatcher/handler.go
  pkg/channel/distributed/dispatcher/dispatcher/handler_test.go
  pkg/channel/distributed/receiver/README.md
  pkg/common/consumer/testing/mocks.go
Labels: approved, cla: yes, lgtm, size/XL

#649 Mark KafkaSource as ready when all initial offsets have been committed
  pkg/apis/sources/v1beta1/kafka_lifecycle.go
  pkg/apis/sources/v1beta1/kafka_lifecycle_test.go
  pkg/source/adapter/adapter.go
  pkg/source/adapter/adapter_test.go
  pkg/source/client/client.go
  pkg/source/client/offsets.go
  pkg/source/client/offsets_test.go
  pkg/source/mtadapter/adapter.go
  pkg/source/reconciler/mtsource/kafkasource.go
  pkg/source/reconciler/source/kafkasource.go
  test/e2e/kafka_source.go
  test/e2e/kafka_source_test.go
  test/rekt/features/kafkasource/data_plane.go
Labels: approved, cla: yes, lgtm, size/XL

#711 skip dls test
  test/conformance/channel_status_subscriber_test.go
  test/e2e/channel_dls_test.go
Labels: approved, cla: yes, lgtm, size/XS

#710 Add resource requests and limits to kafka-webhook
  config/channel/webhook/webhook-deployment.yaml
Labels: approved, cla: yes, lgtm, size/XS

#701 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/cleanhttp.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/handlers.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/Makefile
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/client.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/roundtripper.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/.travis.yml
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/uuid.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#718 Update control-protocol version
  go.mod
  go.sum
  pkg/source/reconciler/source/kafkasource.go
  vendor/knative.dev/control-protocol/pkg/reconciler/async_command_notification_store.go
  vendor/knative.dev/control-protocol/pkg/reconciler/connection_pool.go
  vendor/knative.dev/control-protocol/pkg/reconciler/connection_pool_option.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#560 Add mt-tenant e2e test
  test/rekt/features/kafkasource/mt_data_plane.go
  test/rekt/kafka_source_test.go
Labels: approved, cla: yes, lgtm, size/L

#719 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/k8s.io/apiserver/pkg/storage/names/LICENSE
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/factory.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/eventing/test/e2e_flags.go
  vendor/knative.dev/eventing/test/flags/eventing_environment.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/test/environment/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#715 Avoid copying msg when extracting the event type
  pkg/channel/consolidated/dispatcher/consumer_message_handler.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#705 [scheduler] Compact vreplicas
  pkg/common/scheduler/scheduler.go
  pkg/common/scheduler/statefulset/autoscaler.go
  pkg/common/scheduler/statefulset/autoscaler_test.go
  pkg/common/scheduler/statefulset/scheduler.go
  pkg/source/reconciler/mtsource/controller.go
Labels: approved, cla: yes, lgtm, size/L

#721 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#726 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/conformance/helpers/channel_spec_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_subscriber_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_test_helper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#727 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#714 Add permission to update namespace finalizer
  config/channel/webhook/webhook-clusterrole.yaml
  config/source/single/roles/clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/S

#730 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/delivery_conversion.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/api_validation.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/feature/store.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/recorder_vent/recorder.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#729 Fix no kafka channel address issue
  pkg/channel/consolidated/utils/util.go
  pkg/channel/consolidated/utils/util_test.go
Labels: approved, cla: yes, lgtm, size/S

#732 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#728 [Scheduler] Prevent pod to be overcommitted
  pkg/common/scheduler/statefulset/autoscaler.go
  pkg/common/scheduler/statefulset/autoscaler_test.go
  pkg/common/scheduler/statefulset/scheduler.go
  pkg/common/scheduler/statefulset/state.go
  pkg/common/scheduler/statefulset/state_test.go
Labels: approved, cla: yes, lgtm, size/L

#733 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#734 [main] Upgrade to latest dependencies
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/cleanhttp.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/handlers.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/Makefile
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/client.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/roundtripper.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/.travis.yml
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/uuid.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
Labels: approved, cla: yes, lgtm, size/XS

#735 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_message_handler.go
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#736 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/XS

#737 Update to sarama 1.29.1
  go.mod
  go.sum
  vendor/github.com/Shopify/sarama/acl_types.go
  vendor/github.com/Shopify/sarama/alter_configs_response.go
  vendor/github.com/Shopify/sarama/broker.go
  vendor/github.com/Shopify/sarama/consumer.go
  vendor/github.com/Shopify/sarama/consumer_group.go
  vendor/github.com/Shopify/sarama/go.mod
  vendor/github.com/Shopify/sarama/go.sum
  vendor/github.com/Shopify/sarama/gssapi_kerberos.go
  vendor/github.com/Shopify/sarama/incremental_alter_configs_request.go
  vendor/github.com/Shopify/sarama/incremental_alter_configs_response.go
  vendor/github.com/Shopify/sarama/request.go
  vendor/golang.org/x/net/http2/ascii.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_linux_386.go
  vendor/golang.org/x/sys/unix/syscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/syscall_linux_mips64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_mipsx.go
  vendor/golang.org/x/sys/unix/syscall_linux_ppc.go
  vendor/golang.org/x/sys/unix/syscall_linux_ppc64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_linux_s390x.go
  vendor/golang.org/x/sys/unix/syscall_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/ztypes_dragonfly_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_386.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_arm.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_386.go
  vendor/golang.org/x/sys/unix/ztypes_linux_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mipsle.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
  vendor/golang.org/x/sys/unix/ztypes_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_netbsd_386.go
  vendor/golang.org/x/sys/unix/ztypes_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_netbsd_arm.go
  vendor/golang.org/x/sys/unix/ztypes_netbsd_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_openbsd_386.go
  vendor/golang.org/x/sys/unix/ztypes_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_openbsd_arm.go
  vendor/golang.org/x/sys/unix/ztypes_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_openbsd_mips64.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#738 [rekt] KafkaSource readiness test requires a topic
  test/rekt/features/kafkasource/readiness.go
  test/rekt/kafka_source_test.go
Labels: approved, cla: yes, lgtm, size/S

#725 Resetoffset controller control protocol
  pkg/channel/distributed/controller/util/dispatcher.go
  pkg/channel/distributed/controller/util/subscription.go
  pkg/channel/distributed/controller/util/subscription_test.go
  pkg/common/commands/resetoffset/controller/controller.go
  pkg/common/commands/resetoffset/controller/controller_test.go
  pkg/common/commands/resetoffset/controller/dataplane.go
  pkg/common/commands/resetoffset/controller/dataplane_test.go
  pkg/common/commands/resetoffset/controller/offsets.go
  pkg/common/commands/resetoffset/controller/offsets_test.go
  pkg/common/commands/resetoffset/controller/reconciler.go
  pkg/common/commands/resetoffset/controller/reconciler_test.go
  pkg/common/commands/resetoffset/controller/testing/data.go
  pkg/common/commands/resetoffset/controller/testing/mock.go
  pkg/common/commands/resetoffset/refmappers/subscription.go
  pkg/common/commands/resetoffset/refmappers/subscription_test.go
  pkg/common/commands/resetoffset/refmappers/testing/data.go
  pkg/common/commands/resetoffset/refmappers/testing/mocks.go
  pkg/common/commands/resetoffset/refmappers/types.go
  pkg/common/controlprotocol/commands/consumergroup.go
  pkg/common/controlprotocol/commands/consumergroup_test.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/fake/fake.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#724 Create stop/start ConsumerGroup Manager with Control-Protocol
  cmd/channel/distributed/dispatcher/main.go
  pkg/channel/distributed/common/kafka/consumer/consumer_test.go
  pkg/channel/distributed/common/kafka/testing/mocks.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
  pkg/common/consumer/consumer_factory.go
  pkg/common/consumer/consumer_factory_test.go
  pkg/common/consumer/consumer_manager.go
  pkg/common/consumer/consumer_manager_test.go
  pkg/common/consumer/managed_group.go
  pkg/common/consumer/managed_group_test.go
  pkg/common/consumer/testing/mocks.go
  pkg/common/controlprotocol/controlprotocol.go
  pkg/common/controlprotocol/controlprotocol_test.go
  pkg/common/controlprotocol/testing/mocks.go
  pkg/common/kafka/testing/mocks.go
Labels: approved, cla: yes, lgtm, size/XXL

#741 Resetoffset Controller - Reconciler Lifecycle & Locks
  pkg/apis/kafka/v1alpha1/reset_offset_lifecycle.go
  pkg/apis/kafka/v1alpha1/reset_offset_lifecycle_test.go
  pkg/common/commands/resetoffset/controller/controller.go
  pkg/common/commands/resetoffset/controller/controller_test.go
  pkg/common/commands/resetoffset/controller/dataplane.go
  pkg/common/commands/resetoffset/controller/dataplane_test.go
  pkg/common/commands/resetoffset/controller/reconciler.go
  pkg/common/commands/resetoffset/controller/reconciler_test.go
  pkg/common/commands/resetoffset/controller/testing/data.go
  pkg/common/commands/resetoffset/controller/testing/mock.go
  pkg/common/commands/resetoffset/controller/util.go
  pkg/common/commands/resetoffset/controller/util_test.go
  pkg/common/controlprotocol/commands/consumergroup.go
  pkg/common/controlprotocol/commands/consumergroup_test.go
  pkg/common/controlprotocol/commands/lock.go
  pkg/common/controlprotocol/commands/lock_test.go
  pkg/common/controlprotocol/controlprotocol_test.go
  pkg/common/controlprotocol/testing/mocks.go
Labels: approved, cla: yes, lgtm, size/XXL

#742 Lock unlock protocol flags
  pkg/common/consumer/consumer_manager.go
  pkg/common/consumer/consumer_manager_test.go
  pkg/common/consumer/managed_group.go
  pkg/common/consumer/managed_group_test.go
Labels: approved, cla: yes, lgtm, size/XL

#743 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/upgrade/prober/configuration.go
  vendor/knative.dev/eventing/test/upgrade/prober/prober.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#745 ResetOffset - Preliminary README Docs
  config/command/resources/RESET_OFFSET.md
  pkg/channel/distributed/README.md
  pkg/common/commands/resetoffset/README.md
  pkg/common/commands/resetoffset/controller/dataplane.go
Labels: approved, cla: yes, lgtm, size/L

#746 Fix stop start without locking
  pkg/common/consumer/consumer_manager.go
  pkg/common/consumer/consumer_manager_test.go
  pkg/common/consumer/managed_group.go
  pkg/common/consumer/managed_group_test.go
Labels: approved, cla: yes, lgtm, size/XL
