Repository knative-extensions/eventing-kafka, pull requests merged in 2021-12, with the labels that each got.

#1009 Fix array comparison in tracing unit test.
  pkg/common/tracing/tracing_test.go
Labels: cla: yes, size/XS, lgtm, approved

#1010 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/XS, lgtm, approved

#1011 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/XS, lgtm, approved

#1012 SourceCRDRegistryTest
  test/conformance/source_crd_registry_test.go
Labels: cla: yes, lgtm, approved, size/M

#1015 Bump Sarama to 1.30.1
  go.mod
  go.sum
  vendor/github.com/Shopify/sarama/CHANGELOG.md
  vendor/github.com/Shopify/sarama/README.md
  vendor/github.com/Shopify/sarama/compress.go
  vendor/github.com/Shopify/sarama/consumer.go
  vendor/github.com/Shopify/sarama/decompress.go
  vendor/github.com/Shopify/sarama/docker-compose.yml
  vendor/github.com/Shopify/sarama/fetch_response.go
  vendor/github.com/Shopify/sarama/go.mod
  vendor/github.com/Shopify/sarama/records.go
  vendor/github.com/Shopify/sarama/sarama.go
  vendor/github.com/Shopify/sarama/zstd.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/idna/go118.go
  vendor/golang.org/x/net/idna/idna10.0.0.go
  vendor/golang.org/x/net/idna/idna9.0.0.go
  vendor/golang.org/x/net/idna/pre_go118.go
  vendor/golang.org/x/net/idna/punycode.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/L

#1016 Fix rekt compile errors
  go.mod
  go.sum
  test/rekt/resources/kafkatopic/topic.go
  test/rekt/resources/resetoffset/resetoffset.go
  vendor/knative.dev/reconciler-test/pkg/k8s/job.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#1018 Remove duplicated yaml anchors for simpler files
  config/source/multi/roles/clusterrole.yaml
  config/source/single/roles/clusterrole.yaml
Labels: cla: yes, lgtm, approved, size/M

#1019 Comment out test that always fails
  test/e2e/helpers/kafka_source_test_helper.go
Labels: lgtm, approved, size/S

#1022 Adding CRD / RBAC test
  test/conformance/source_crd_rbac_test.go
Labels: lgtm, approved, size/M

#1021 Updating to 0.26 of Strimzi
  test/config/100-strimzi-cluster-operator-0.26.0.yaml
  test/e2e-common.sh
Labels: lgtm, approved, size/L

#1023 Hello Apache Kafka 3.0.0
  test/config/100-kafka-ephemeral-triple-3.0.0.yaml
  test/e2e-common.sh
Labels: size/XS, lgtm, approved

#1025 Update KafkaChannel CRD to support experimental-features in Delivery
  config/channel/resources/kafkachannel-crd.yaml
Labels: size/XS, lgtm, approved

#1027 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1026 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1028 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#1029 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1031 New Strimzi images
  test/config/100-strimzi-cluster-operator-0.26.1.yaml
  test/e2e-common.sh
Labels: lgtm, approved, size/M

#1033 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1034 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, lgtm, approved

#1036 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1037 Fix ChannelFeatureMap since KafkaChannel is v1beta1 not v1
  test/config.go
Labels: size/XS, lgtm, approved
