Repository knative-extensions/eventing-kafka, pull requests merged in 2021-04, with the labels that each got.

#487 [Consolidated Channel] Update target pod IPs when dispatcher pods scale before the subscription is marked ready
  pkg/channel/consolidated/reconciler/controller/controller.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/lister.go
  pkg/channel/consolidated/status/status.go
  pkg/channel/consolidated/status/status_test.go
Labels: approved, cla: yes, lgtm, size/L

#496 [v0.20] [Consolidated Channel] Backport of #487
  pkg/channel/consolidated/reconciler/controller/controller.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/lister.go
  pkg/channel/consolidated/status/status.go
  pkg/channel/consolidated/status/status_test.go
Labels: approved, cla: yes, lgtm, size/L

#510 Dependency update and some hack/test
  go.mod
  go.sum
  test/e2e-common.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M

#512 [0.22] undo the hack, part of #510
  test/e2e-common.sh
Labels: cla: yes, lgtm, size/M

#511 [Consolidated] Pass ServiceAccount to use in consolidated channel via an env var
  config/channel/consolidated/deployments/controller.yaml
  pkg/channel/consolidated/reconciler/controller/controller.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel_test.go
  pkg/channel/consolidated/reconciler/controller/resources/dispatcher.go
  pkg/channel/consolidated/reconciler/controller/resources/dispatcher_test.go
  pkg/channel/consolidated/reconciler/controller/resources/role_binding_test.go
  pkg/channel/consolidated/reconciler/controller/resources/service_account_test.go
Labels: cla: yes, lgtm, size/M

#328 [KafkaSource] Use the control protocol to expose the consumer group status
  go.mod
  go.sum
  pkg/apis/sources/v1alpha1/kafka_conversion.go
  pkg/apis/sources/v1alpha1/kafka_types.go
  pkg/apis/sources/v1beta1/kafka_lifecycle.go
  pkg/apis/sources/v1beta1/kafka_types.go
  pkg/channel/consolidated/dispatcher/dispatcher_test.go
  pkg/common/consumer/consumer_factory.go
  pkg/common/consumer/consumer_handler.go
  pkg/source/adapter/adapter.go
  pkg/source/control/message.go
  pkg/source/reconciler/source/controller.go
  pkg/source/reconciler/source/kafkasource.go
  pkg/source/reconciler/source/resources/labels.go
  pkg/source/reconciler/source/resources/receive_adapter.go
  test/e2e/kafka_source_claims_test.go
  test/e2e/kafka_source_test.go
  third_party/VENDOR-LICENSE/knative.dev/control-protocol/pkg/LICENSE
  vendor/knative.dev/control-protocol/LICENSE
  vendor/knative.dev/control-protocol/pkg/certificates/certs.go
  vendor/knative.dev/control-protocol/pkg/certificates/constants.go
  vendor/knative.dev/control-protocol/pkg/certificates/key_pair.go
  vendor/knative.dev/control-protocol/pkg/connection.go
  vendor/knative.dev/control-protocol/pkg/doc.go
  vendor/knative.dev/control-protocol/pkg/message.go
  vendor/knative.dev/control-protocol/pkg/network/base_connection.go
  vendor/knative.dev/control-protocol/pkg/network/client_connection.go
  vendor/knative.dev/control-protocol/pkg/network/constants.go
  vendor/knative.dev/control-protocol/pkg/network/server_connection.go
  vendor/knative.dev/control-protocol/pkg/network/tls.go
  vendor/knative.dev/control-protocol/pkg/reconciler/connection_pool.go
  vendor/knative.dev/control-protocol/pkg/reconciler/connection_pool_option.go
  vendor/knative.dev/control-protocol/pkg/reconciler/notification_store.go
  vendor/knative.dev/control-protocol/pkg/reconciler/pod_ip_getter.go
  vendor/knative.dev/control-protocol/pkg/reconciler/tls_dialer_factory.go
  vendor/knative.dev/control-protocol/pkg/service.go
  vendor/knative.dev/control-protocol/pkg/service/handlers.go
  vendor/knative.dev/control-protocol/pkg/service/message_router.go
  vendor/knative.dev/control-protocol/pkg/service/service.go
  vendor/knative.dev/control-protocol/pkg/service/service_caching_wrapper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#486 Global resync Kafka channels when config-kafka is changed
  pkg/channel/consolidated/reconciler/controller/controller.go
Labels: approved, cla: yes, lgtm, size/S

#509 [Consolidated] Rewrote the dispatcher reconciler
  pkg/channel/consolidated/dispatcher/config.go
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
  pkg/channel/consolidated/dispatcher/dispatcher_test.go
  pkg/channel/consolidated/dispatcher/kafka_subscription.go
  pkg/channel/consolidated/dispatcher/subscription_endpoint.go
  pkg/channel/consolidated/dispatcher/subscription_endpoint_test.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
Labels: cla: yes, lgtm, size/XL

#523 disable control server when running the mt source.
  config/source/multi/201-adapter-clusterrole.yaml
  pkg/source/adapter/adapter.go
  pkg/source/mtadapter/adapter.go
Labels: approved, cla: yes, lgtm, size/S

#526 [v0.20] Adding dummy e2e-upgrade-test
  test/e2e-upgrade-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#497 [v0.21] [Consolidated Channel] Backport of #487
  pkg/channel/consolidated/reconciler/controller/controller.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/lister.go
  pkg/channel/consolidated/status/status.go
  pkg/channel/consolidated/status/status_test.go
  pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/controller.go
  pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/reconciler.go
  pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/controller.go
  pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/controller.go
  pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/controller.go
  pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/kafkasource/controller.go
  pkg/client/injection/reconciler/sources/v1beta1/kafkasource/reconciler.go
  test/e2e-upgrade-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#520 [0.20] Backport of #509
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
  pkg/channel/consolidated/dispatcher/dispatcher_test.go
  pkg/channel/consolidated/dispatcher/kafka_subscription.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
Labels: approved, cla: yes, lgtm, size/XL

#521 [0.21] Backport of #509
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
  pkg/channel/consolidated/dispatcher/dispatcher_test.go
  pkg/channel/consolidated/dispatcher/kafka_subscription.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
Labels: cla: yes, lgtm, size/XL

#524 Run KafkaSource smokes in upgrade test
  test/e2e-common.sh
  test/e2e/kafka_source.go
  test/e2e/kafka_source_test.go
  test/upgrade/README.md
  test/upgrade/continual.go
  test/upgrade/installation/githead.go
  test/upgrade/installation/stable.go
  test/upgrade/postdowngrade.go
  test/upgrade/postupgrade.go
  test/upgrade/preupgrade.go
  test/upgrade/smoke.go
  test/upgrade/suite.go
Labels: approved, cla: yes, lgtm, size/XXL

#505 [MTSource] ST Adapter start returns error instead of panic
  pkg/source/adapter/adapter.go
  pkg/source/adapter/adapter_test.go
  pkg/source/mtadapter/adapter_test.go
Labels: approved, cla: yes, lgtm, size/M

#514 [consolidated] Rolling deployment dispatcher on configmap change
  config/channel/consolidated/deployments/dispatcher.yaml
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel_test.go
  pkg/channel/consolidated/reconciler/controller/resources/dispatcher.go
  pkg/channel/consolidated/reconciler/controller/resources/dispatcher_test.go
  pkg/channel/consolidated/reconciler/controller/resources/service_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#528 [Automated] Format markdown
  test/upgrade/README.md
Labels: approved, cla: yes, lgtm, size/XS

#529 Distributed channel - watch config-kafka like consolidated channel
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/distributed/controller/kafkachannel/controller.go
  pkg/channel/distributed/controller/kafkachannel/reconciler.go
Labels: approved, cla: yes, lgtm, size/M

#534 [0.21] Backport of #525
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  pkg/channel/distributed/common/config/secretwatcher.go
  pkg/channel/distributed/common/config/secretwatcher_test.go
  pkg/channel/distributed/receiver/producer/producer.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#535 [0.22] Backport of #525
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  pkg/channel/distributed/common/config/secretwatcher.go
  pkg/channel/distributed/common/config/secretwatcher_test.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/receiver/producer/producer.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#470 [mtsource] Automatically adjust Sarama resource usage to fit within limits
  config/source/multi/deployments/adapter.yaml
  config/source/multi/deployments/controller.yaml
  pkg/common/scheduler/placement.go
  pkg/common/scheduler/placement_test.go
  pkg/source/client/client.go
  pkg/source/mtadapter/adapter.go
  pkg/source/mtadapter/adapter_test.go
  pkg/source/reconciler/mtsource/controller.go
Labels: cla: yes, lgtm, size/L

#537 Distributed channel - config-kafka reloading
  cmd/channel/consolidated/dispatcher/main.go
  cmd/channel/distributed/controller/main.go
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  config/channel/distributed/500-controller-deployment.yaml
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel_test.go
  pkg/channel/consolidated/reconciler/controller/resources/dispatcher.go
  pkg/channel/consolidated/reconciler/controller/resources/dispatcher_test.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
  pkg/channel/distributed/common/kafka/sarama/sarama.go
  pkg/channel/distributed/common/kafka/sarama/sarama_test.go
  pkg/channel/distributed/controller/kafkachannel/controller.go
  pkg/channel/distributed/controller/kafkachannel/controller_test.go
  pkg/channel/distributed/controller/kafkachannel/dispatcher.go
  pkg/channel/distributed/controller/kafkachannel/reconciler.go
  pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
  pkg/channel/distributed/controller/kafkasecret/controller.go
  pkg/channel/distributed/controller/kafkasecret/controller_test.go
  pkg/channel/distributed/controller/kafkasecret/receiver.go
  pkg/channel/distributed/controller/kafkasecret/reconciler.go
  pkg/channel/distributed/controller/kafkasecret/reconciler_test.go
  pkg/channel/distributed/controller/testing/data.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel_test.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
  pkg/channel/distributed/receiver/producer/producer.go
  pkg/channel/distributed/receiver/producer/producer_test.go
  pkg/common/config/util.go
  pkg/common/config/util_test.go
  pkg/common/configmaploader/configmapLoader.go
  pkg/common/configmaploader/fake/configmapLoader.go
  pkg/common/constants/constants.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#542 Remove unused Kafka dispatcher arg
  pkg/channel/consolidated/dispatcher/dispatcher.go
Labels: approved, cla: yes, lgtm, size/XS

#543 Fix linter complaining
  go.mod
  go.sum
  test/test_images/kafka_performance/kafka_load_generator.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#540 [QE] Setting retries & replication options with easy customization for upgrade tests
  test/upgrade/continual.go
  test/upgrade/suite.go
Labels: approved, cla: yes, lgtm, size/L

#551 Only return true in probe verifier if all partitions found
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/status/status.go
Labels: approved, cla: yes, lgtm, size/M

#555 [Consolidated Channel] Fix a bad log line
  pkg/channel/consolidated/status/status.go
Labels: approved, cla: yes, lgtm, size/XS

#550 Remove KafkaChannel v1alpha1
  config/channel/resources/kafkachannel-crd.yaml
  config/post-install/clusterrole.yaml
  config/post-install/placeholder.go
  config/post-install/serviceaccount.yaml
  config/post-install/storage-version-migrator.yaml
  hack/update-codegen.sh
  pkg/apis/duck/v1alpha1/channelable_combined_types.go
  pkg/apis/duck/v1alpha1/channelable_combined_types_test.go
  pkg/apis/duck/v1alpha1/channelable_types.go
  pkg/apis/duck/v1alpha1/channelable_types_test.go
  pkg/apis/duck/v1alpha1/subscribable_types.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go
  pkg/apis/duck/v1alpha1/subscribable_types_test.go
  pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/messaging/v1alpha1/doc.go
  pkg/apis/messaging/v1alpha1/kafka_channel_conversion.go
  pkg/apis/messaging/v1alpha1/kafka_channel_conversion_test.go
  pkg/apis/messaging/v1alpha1/kafka_channel_defaults.go
  pkg/apis/messaging/v1alpha1/kafka_channel_defaults_test.go
  pkg/apis/messaging/v1alpha1/kafka_channel_lifecycle.go
  pkg/apis/messaging/v1alpha1/kafka_channel_lifecycle_test.go
  pkg/apis/messaging/v1alpha1/kafka_channel_types.go
  pkg/apis/messaging/v1alpha1/kafka_channel_types_test.go
  pkg/apis/messaging/v1alpha1/kafka_channel_validation.go
  pkg/apis/messaging/v1alpha1/kafka_channel_validation_test.go
  pkg/apis/messaging/v1alpha1/register.go
  pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go
  pkg/channel/webhook/controller.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/fake/fake_kafkachannel.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/fake/fake_messaging_client.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/kafkachannel.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/messaging_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/messaging/interface.go
  pkg/client/informers/externalversions/messaging/v1alpha1/interface.go
  pkg/client/informers/externalversions/messaging/v1alpha1/kafkachannel.go
  pkg/client/injection/informers/messaging/v1alpha1/kafkachannel/fake/fake.go
  pkg/client/injection/informers/messaging/v1alpha1/kafkachannel/filtered/fake/fake.go
  pkg/client/injection/informers/messaging/v1alpha1/kafkachannel/filtered/kafkachannel.go
  pkg/client/injection/informers/messaging/v1alpha1/kafkachannel/kafkachannel.go
  pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/state.go
  pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/stub/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/stub/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/stub/controller.go
  pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/stub/reconciler.go
  pkg/client/listers/messaging/v1alpha1/expansion_generated.go
  pkg/client/listers/messaging/v1alpha1/kafkachannel.go
  test/conformance/README.md
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/XXL

#548 Restart distributed deployments when changed
  pkg/channel/distributed/controller/constants/constants.go
  pkg/channel/distributed/controller/event/event.go
  pkg/channel/distributed/controller/event/event_test.go
  pkg/channel/distributed/controller/kafkachannel/dispatcher.go
  pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
  pkg/channel/distributed/controller/kafkasecret/receiver.go
  pkg/channel/distributed/controller/kafkasecret/reconciler_test.go
  pkg/channel/distributed/controller/testing/data.go
  pkg/channel/distributed/controller/testing/factory.go
  pkg/channel/distributed/controller/util/compare.go
  pkg/channel/distributed/controller/util/compare_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#476 Dispatcher readiness e2e test
  test/e2e-common.sh
  test/e2e/channel_subscription_ready_test.go
  test/e2e/helpers/channel_subscription_ready_test_helper.go
  test/e2e/helpers/kafka_helper.go
  test/e2e/kafka_binding_test.go
  test/e2e/kafka_source.go
  test/e2e/kafka_source_claims_test.go
  test/e2e/kafka_source_reconciler_test.go
  test/e2e/kafka_source_test.go
  test/lib/creation.go
  test/lib/setupclientoptions/sources.go
Labels: cla: yes, lgtm, size/L

#568 Drop --strict flag on ko
  config/channel/distributed/README.md
  docs/kind_kafka_cluster.md
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#573 [Consolidated Channel] Skipping subscription readiness test when scaling dispatcher
  test/e2e/channel_subscription_ready_test.go
Labels: approved, cla: yes, lgtm, size/XS

#566 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/reconciler.go
  pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/kafkasource/reconciler.go
  vendor/knative.dev/control-protocol/pkg/service/message_router.go
  vendor/knative.dev/control-protocol/pkg/service/service.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e_flags.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#571 [Automated] Format markdown
  config/channel/distributed/README.md
Labels: approved, cla: yes, lgtm, size/XS

#565 Missing defer close kafka admin client in FinalizeKind
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
Labels: approved, cla: yes, lgtm, size/XS

#575 Reducing noise of the 'Changes detected' logger
  pkg/channel/consolidated/reconciler/controller/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#579 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#580 Upgrade deps
  go.mod
  go.sum
  pkg/source/reconciler/source/controller.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_context.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/apiserversource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_apiserversource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_sources_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/sources_client.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/v1alpha1/apiserversource.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/v1alpha1/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/v1alpha1/sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1alpha1/apiserversource.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1alpha1/expansion_generated.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1alpha1/sinkbinding.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/sinkbinding.go
  vendor/knative.dev/eventing/test/e2e_flags.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/XXL

#581 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, size/S

#585 Adding generated openAPIV3Schema from hack tool (not embedded)
  config/channel/resources/kafkachannel-crd.yaml
Labels: approved, cla: yes, lgtm, size/L

#586 Remove istio sidecar annotation
  pkg/source/reconciler/source/resources/receive_adapter.go
  pkg/source/reconciler/source/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/S

#591 Copy volumes as well as container when creating deployment updates
  pkg/channel/distributed/controller/util/compare.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
