Repository knative-extensions/eventing-kafka, pull requests merged in 2021-09, with the labels that each got.

#844 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_validation.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#847 Make configmap reading func exported
  pkg/common/kafka/sarama/sarama.go
Labels: cla: yes, size/XS, lgtm, approved

#849 [release-0.25] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/L

#848 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/L

#850 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/reconciler/leader.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/L

#851 [release-0.24] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/L

#853 [release-0.23] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_spec_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_subscriber_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_test_helper.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/L

#857 Make status.address optional in the KafkaChannel CRD
  config/channel/resources/kafkachannel-crd.yaml
Labels: cla: yes, size/XS, lgtm, approved

#856 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#855 Add Kafka Source defaults, starting with KEDA annotations
  cmd/source/controller/main.go
  cmd/source/mtcontroller/main.go
  config/source/common/configmaps/config-kafka-source-defaults.yaml
  config/source/multi/400-config-kafka-source-defaults.yaml
  config/source/single/400-config-kafka-source-defaults.yaml
  hack/tools.go
  hack/update-checksums.sh
  pkg/apis/sources/config/doc.go
  pkg/apis/sources/config/kafka_defaults.go
  pkg/apis/sources/config/kafka_defaults_test.go
  pkg/apis/sources/config/store.go
  pkg/apis/sources/config/store_test.go
  pkg/apis/sources/config/testdata/config-kafka-source-defaults.yaml
  pkg/apis/sources/v1beta1/kafka_defaults.go
  pkg/apis/sources/v1beta1/kafka_defaults_test.go
  vendor/knative.dev/pkg/configmap/hash-gen/main.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/modules.txt
Labels: cla: yes, size/XXL, lgtm, approved

#852 [release-0.22] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_conversion.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/upgrade/prober/forwarder.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/L

#768 Next generation MT Scheduler and Descheduler with pluggable policies
  config/source/common/configmaps/config-descheduler.yaml
  config/source/common/configmaps/config-scheduler.yaml
  config/source/multi/400-config-descheduler.yaml
  config/source/multi/400-config-scheduler.yaml
  config/source/multi/deployments/adapter.yaml
  config/source/multi/deployments/controller.yaml
  pkg/apis/duck/v1alpha1/placement_types.go
  pkg/apis/sources/v1beta1/kafka_scheduling.go
  pkg/apis/sources/v1beta1/kafka_scheduling_test.go
  pkg/common/constants/constants.go
  pkg/common/scheduler/factory/registry.go
  pkg/common/scheduler/plugins/core/availabilitynodepriority/availability_node_priority.go
  pkg/common/scheduler/plugins/core/availabilitynodepriority/availability_node_priority_test.go
  pkg/common/scheduler/plugins/core/availabilityzonepriority/availability_zone_priority.go
  pkg/common/scheduler/plugins/core/availabilityzonepriority/availability_zone_priority_test.go
  pkg/common/scheduler/plugins/core/evenpodspread/even_pod_spread.go
  pkg/common/scheduler/plugins/core/evenpodspread/even_pod_spread_test.go
  pkg/common/scheduler/plugins/core/lowestordinalpriority/lowest_ordinal_priority.go
  pkg/common/scheduler/plugins/core/lowestordinalpriority/lowest_ordinal_priority_test.go
  pkg/common/scheduler/plugins/core/podfitsresources/pod_fits_resources.go
  pkg/common/scheduler/plugins/core/podfitsresources/pod_fits_resources_test.go
  pkg/common/scheduler/plugins/core/removewithavailabilitynodepriority/remove_with_availability_node_priority.go
  pkg/common/scheduler/plugins/core/removewithavailabilitynodepriority/remove_with_availability_node_priority_test.go
  pkg/common/scheduler/plugins/core/removewithavailabilityzonepriority/remove_with_availability_zone_priority.go
  pkg/common/scheduler/plugins/core/removewithavailabilityzonepriority/remove_with_availability_zone_priority_test.go
  pkg/common/scheduler/plugins/core/removewithevenpodspreadpriority/remove_with_even_pod_spread_priority.go
  pkg/common/scheduler/plugins/core/removewithevenpodspreadpriority/remove_with_even_pod_spread_priority_test.go
  pkg/common/scheduler/plugins/core/removewithhighestordinalpriority/remove_with_highest_ordinal_priority.go
  pkg/common/scheduler/plugins/core/removewithhighestordinalpriority/remove_with_highest_ordinal_priority_test.go
  pkg/common/scheduler/plugins/kafka/nomaxresourcecount/no_max_resource_count.go
  pkg/common/scheduler/plugins/kafka/nomaxresourcecount/no_max_resource_count_test.go
  pkg/common/scheduler/scheduler.go
  pkg/common/scheduler/state/helpers.go
  pkg/common/scheduler/state/interface.go
  pkg/common/scheduler/state/interface_test.go
  pkg/common/scheduler/state/state.go
  pkg/common/scheduler/state/state_test.go
  pkg/common/scheduler/statefulset/autoscaler.go
  pkg/common/scheduler/statefulset/autoscaler_test.go
  pkg/common/scheduler/statefulset/helpers.go
  pkg/common/scheduler/statefulset/scheduler.go
  pkg/common/scheduler/statefulset/scheduler_test.go
  pkg/common/scheduler/statefulset/state.go
  pkg/common/scheduler/statefulset/state_test.go
  pkg/common/scheduler/testing/vpod.go
  pkg/source/README.md
  pkg/source/reconciler/mtsource/controller.go
  pkg/source/reconciler/mtsource/kafkasource.go
Labels: cla: yes, size/XXL, lgtm, approved

#861 [release-0.25] add Kafka defaults, starting with KEDA annotations (#855)
  cmd/source/controller/main.go
  cmd/source/mtcontroller/main.go
  config/source/common/configmaps/config-kafka-source-defaults.yaml
  config/source/multi/400-config-kafka-source-defaults.yaml
  config/source/single/400-config-kafka-source-defaults.yaml
  hack/tools.go
  hack/update-checksums.sh
  pkg/apis/sources/config/doc.go
  pkg/apis/sources/config/kafka_defaults.go
  pkg/apis/sources/config/kafka_defaults_test.go
  pkg/apis/sources/config/store.go
  pkg/apis/sources/config/store_test.go
  pkg/apis/sources/config/testdata/config-kafka-source-defaults.yaml
  pkg/apis/sources/v1beta1/kafka_defaults.go
  pkg/apis/sources/v1beta1/kafka_defaults_test.go
  vendor/knative.dev/pkg/configmap/hash-gen/main.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/modules.txt
Labels: cla: yes, size/XXL, lgtm, approved

#854 fix KafkaSource mt webhook RBAC
  config/source/multi/roles/clusterrole.yaml
Labels: cla: yes, size/XS, lgtm, approved

#858 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/reconciler.go
  pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/state.go
  pkg/client/injection/reconciler/kafka/v1alpha1/resetoffset/reconciler.go
  pkg/client/injection/reconciler/kafka/v1alpha1/resetoffset/state.go
  pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/state.go
  pkg/client/injection/reconciler/sources/v1beta1/kafkasource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/kafkasource/state.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/state.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/L

#863 Add Immutability Validation
  pkg/apis/kafka/v1alpha1/reset_offset_validation.go
  pkg/apis/kafka/v1alpha1/reset_offset_validation_test.go
  pkg/apis/messaging/v1beta1/kafka_channel_validation.go
  pkg/apis/messaging/v1beta1/kafka_channel_validation_test.go
Labels: cla: yes, lgtm, approved, size/L

#865 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#867 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e_flags.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#870 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/XS, lgtm, approved

#866 Updating to Strimzi 0.25 version
  .wokeignore
  test/config/100-strimzi-cluster-operator-0.25.0.yaml
  test/config/100-strimzi-users-0.23.0.yaml
  test/config/100-strimzi-users.yaml
  test/e2e-common.sh
Labels: cla: yes, size/XXL, lgtm, approved

#872 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/S

#873 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, lgtm, approved, size/S

#874 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/channel/attributes/knative_error.go
  vendor/knative.dev/eventing/pkg/channel/message_dispatcher.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#875 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#876 Updating deps to include pkg fix
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#877 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: cla: yes, lgtm, approved, size/S

#878 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/L

#883 Move initOffsets functionality to a common package
  pkg/common/kafka/offset/offsets.go
  pkg/common/kafka/offset/offsets_test.go
  pkg/source/reconciler/mtsource/kafkasource.go
  pkg/source/reconciler/source/kafkasource.go
Labels: cla: yes, lgtm, approved, size/M

#885 [0.24] Move initOffsets functionality to a common package
  pkg/common/kafka/offset/offsets.go
  pkg/common/kafka/offset/offsets_test.go
  pkg/source/reconciler/mtsource/kafkasource.go
  pkg/source/reconciler/source/kafkasource.go
Labels: cla: yes, lgtm, approved, size/M

#882 Fix for [scheduler] Crash when creating state
  config/source/multi/deployments/adapter.yaml
  pkg/common/scheduler/state/state.go
Labels: cla: yes, lgtm, approved, size/M

#815 Add delete deployment permission to kafka channel controller
  config/channel/consolidated/roles/controller-clusterrole.yaml
Labels: cla: yes, size/XS, lgtm, approved

#889 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/S

#879 Fix release labels missing release version because of missing kafka prefix
  config/channel/post-install/200-clusterrole.yaml
  config/channel/post-install/400-kafkachannel-update-job.yaml
  config/channel/webhook/webhook-hpa.yaml
  config/source/common/configmaps/config-kafka-source-defaults.yaml
Labels: cla: yes, lgtm, approved, size/S, ok-to-test

#901 [main] Update community files
  CODE-OF-CONDUCT.md
Labels: cla: yes, lgtm, approved, size/M

#900 Teardown v0.26 KafkaChannel post-install job.
  cmd/channel/post-install/main.go
  cmd/channel/post-install/updater.go
  cmd/channel/post-install/updater_test.go
  config/channel/post-install/100-serviceaccount.yaml
  config/channel/post-install/200-clusterrole.yaml
  config/channel/post-install/200-role.yaml
  config/channel/post-install/300-clusterrolebinding.yaml
  config/channel/post-install/300-rolebinding.yaml
  config/channel/post-install/400-kafkachannel-update-job.yaml
  config/channel/post-install/README.md
Labels: cla: yes, lgtm, approved, size/XL

#903 Adding noop migrator for kafkachannels
  config/channel/post-install/clusterrole.yaml
  config/channel/post-install/placeholder.go
  config/channel/post-install/serviceaccount.yaml
  config/channel/post-install/storage-version-migrator.yaml
Labels: cla: yes, lgtm, approved, size/L

#905 latest of zipkin
  test/config/monitoring.yaml
Labels: cla: yes, size/XS, lgtm, approved

#906 Adding noop migrator for kafkasources
  config/source/post-install/clusterrole.yaml
  config/source/post-install/placeholder.go
  config/source/post-install/serviceaccount.yaml
  config/source/post-install/storage-version-migrator.yaml
Labels: cla: yes, lgtm, approved, size/L, kind/enhancement
