Repository knative-extensions/eventing-kafka, pull requests merged in 2021-03, with the labels that each got.

#418 Stringify the sarama RecordHeader slices for easier log reading
  pkg/channel/distributed/common/kafka/sarama/sarama.go
  pkg/channel/distributed/common/kafka/sarama/sarama_test.go
  pkg/channel/distributed/dispatcher/dispatcher/handler.go
  pkg/channel/distributed/receiver/producer/producer.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#417 Fix distributed multi cert tests
  pkg/common/client/config_test.go
  pkg/common/client/yaml_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#422 Add more approvers as default owners
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#421 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/controller.go
  pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/reconciler.go
  pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/controller.go
  pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/controller.go
  pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/controller.go
  pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/kafkasource/controller.go
  pkg/client/injection/reconciler/sources/v1beta1/kafkasource/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/reconciler/testing/clock.go
  vendor/knative.dev/pkg/source/source_stats_reporter.go
  vendor/knative.dev/pkg/system/clock.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#419 add mtsource owners
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#424 [mtsource] simplify autoscaler + refactor
  pkg/common/scheduler/scheduler.go
  pkg/common/scheduler/statefulset/autoscaler.go
  pkg/common/scheduler/statefulset/autoscaler_test.go
  pkg/common/scheduler/statefulset/scheduler.go
  pkg/common/scheduler/statefulset/scheduler_test.go
  pkg/common/scheduler/statefulset/snapshot.go
  pkg/common/scheduler/statefulset/snapshot_test.go
  pkg/common/scheduler/statefulset/state.go
  pkg/common/scheduler/statefulset/state_test.go
  pkg/common/scheduler/testing/client.go
  pkg/common/scheduler/testing/vpod.go
  pkg/source/reconciler/mtsource/controller.go
Labels: cla: yes, lgtm, size/XXL

#427 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/pkg/adapter/v2/test/test_client.go
  vendor/knative.dev/pkg/configmap/informer/informed_watcher.go
  vendor/knative.dev/pkg/configmap/informer/synced_callback.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#429 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#431 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#423 Watch kafka config in consolidated channel controller
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  pkg/channel/consolidated/reconciler/controller/controller.go
  pkg/channel/distributed/common/config/observability_test.go
  pkg/channel/distributed/common/config/secretwatcher_test.go
  pkg/channel/distributed/common/config/tracing_test.go
  pkg/channel/distributed/common/k8s/context_test.go
  pkg/channel/distributed/common/kafka/sarama/sarama.go
  pkg/channel/distributed/common/kafka/sarama/sarama_test.go
  pkg/channel/distributed/controller/config/config.go
  pkg/channel/distributed/controller/config/config_test.go
  pkg/channel/distributed/controller/kafkachannel/controller.go
  pkg/channel/distributed/controller/kafkachannel/controller_test.go
  pkg/channel/distributed/controller/kafkachannel/reconciler.go
  pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
  pkg/channel/distributed/controller/kafkasecret/controller_test.go
  pkg/channel/distributed/controller/kafkasecret/reconciler.go
  pkg/channel/distributed/controller/kafkasecret/reconciler_test.go
  pkg/channel/distributed/controller/kafkasecretinformer/kafkasecretinformer_test.go
  pkg/channel/distributed/controller/testing/data.go
  pkg/channel/distributed/controller/util/channel.go
  pkg/channel/distributed/controller/util/channel_test.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
  pkg/channel/distributed/receiver/producer/producer.go
  pkg/channel/distributed/receiver/producer/producer_test.go
  pkg/common/client/config_test.go
  pkg/common/client/testing/util.go
  pkg/common/config/eventingkafkaconfig.go
  pkg/common/config/kafkaconfigmapwatcher.go
  pkg/common/config/kafkaconfigmapwatcher_test.go
  pkg/common/config/testing/util.go
  pkg/common/testing/constants.go
  pkg/common/testing/util.go
Labels: approved, cla: yes, lgtm, size/L

#430 move eventing/pkg/apis/duck/v1alpha1 here
  go.mod
  go.sum
  pkg/apis/duck/v1alpha1/channelable_combined_types.go
  pkg/apis/duck/v1alpha1/channelable_combined_types_test.go
  pkg/apis/duck/v1alpha1/channelable_types.go
  pkg/apis/duck/v1alpha1/channelable_types_test.go
  pkg/apis/duck/v1alpha1/subscribable_types.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go
  pkg/apis/duck/v1alpha1/subscribable_types_test.go
  pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/messaging/v1alpha1/kafka_channel_conversion.go
  pkg/apis/messaging/v1alpha1/kafka_channel_conversion_test.go
  pkg/apis/messaging/v1alpha1/kafka_channel_types.go
  pkg/apis/messaging/v1alpha1/kafka_channel_validation_test.go
  pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go
  test/e2e-common.sh
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/resource_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/channelable.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/factory.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/listers.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_spec_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_subscriber_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#436 Run all actions against main
  .github/workflows/kind-e2e.yaml
Labels: cla: yes, lgtm, size/XS

#439 Remove trailing dashes from labels
  pkg/channel/distributed/common/k8s/util.go
  pkg/channel/distributed/common/k8s/util_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#440 Use CE connection args available, instead of hardcoded values
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
Labels: approved, cla: yes, lgtm, size/S

#441 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/README.md
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/presubmit-tests.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, size/S

#437 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: cla: yes, lgtm, size/XS

#443 [source] spec.consumers is now mutable
  pkg/apis/sources/v1beta1/kafka_validation.go
  pkg/apis/sources/v1beta1/kafka_validation_test.go
Labels: approved, cla: yes, lgtm, size/M

#446 Upgraded storage version of kafkachannel
  config/channel/resources/kafkachannel-crd.yaml
  pkg/apis/messaging/v1alpha1/kafka_channel_defaults.go
  pkg/apis/messaging/v1alpha1/kafka_channel_defaults_test.go
Labels: approved, cla: yes, lgtm, size/S

#449 Move setting CE connection args setting one level above in consolidated dispatcher
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
Labels: approved, cla: yes, lgtm, size/S

#450 Reorganize consolidated dispatcher code, no behavior change
  pkg/channel/consolidated/dispatcher/config.go
  pkg/channel/consolidated/dispatcher/consumer_message_handler.go
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/kafka_subscription.go
  pkg/channel/consolidated/dispatcher/subscription.go
Labels: approved, cla: yes, lgtm, size/L

#454 fix codeowners for the mtsource code
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#457 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#458 Add label selector to enable HPA to scale Kafka source (seond attempt)
  config/source/multi/resources/kafkasource.yaml
  config/source/single/resources/kafkasource.yaml
  pkg/apis/sources/v1alpha1/kafka_conversion.go
  pkg/apis/sources/v1alpha1/kafka_types.go
  pkg/apis/sources/v1beta1/kafka_types.go
  pkg/source/reconciler/mtsource/kafkasource.go
  pkg/source/reconciler/source/kafkasource.go
  pkg/source/reconciler/source/resources/labels.go
  pkg/source/reconciler/source/resources/labels_test.go
Labels: approved, cla: yes, lgtm, size/M

#456 reduce apiserver requests for dispatcher
  pkg/channel/distributed/dispatcher/controller/kafkachannel.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#465 [Automated] Update actions
  .github/workflows/knative-security.yaml
Labels: approved, cla: yes, lgtm, size/XS

#468 capacity and refreshPeriod are now configurable via env vars
  config/source/multi/deployments/adapter.yaml
  config/source/multi/deployments/controller.yaml
  pkg/common/scheduler/statefulset/autoscaler.go
  pkg/common/scheduler/statefulset/autoscaler_test.go
  pkg/common/scheduler/statefulset/scheduler.go
  pkg/common/scheduler/statefulset/state.go
  pkg/source/reconciler/mtsource/controller.go
Labels: cla: yes, lgtm, size/M

#471 Do not mark messages as consumed if the context was canceled
  pkg/channel/distributed/dispatcher/dispatcher/handler.go
  pkg/channel/distributed/dispatcher/dispatcher/handler_test.go
  pkg/channel/distributed/dispatcher/testing/mocks.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#473 Post install script, part 2
  config/post-install/clusterrole.yaml
  config/post-install/storage-version-migrator.yaml
Labels: approved, cla: yes, lgtm, size/XS

#433 Add Subscription prober
  config/channel/consolidated/deployments/dispatcher.yaml
  config/channel/consolidated/roles/controller-clusterrole.yaml
  go.mod
  go.sum
  pkg/channel/consolidated/dispatcher/consumer_message_handler.go
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/dispatcher_test.go
  pkg/channel/consolidated/dispatcher/kafka_subscription.go
  pkg/channel/consolidated/kafka/admin.go
  pkg/channel/consolidated/kafka/admin_test.go
  pkg/channel/consolidated/reconciler/controller/consumer_group_watcher.go
  pkg/channel/consolidated/reconciler/controller/consumer_group_watcher_test.go
  pkg/channel/consolidated/reconciler/controller/controller.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel_test.go
  pkg/channel/consolidated/reconciler/controller/lister.go
  pkg/channel/consolidated/status/status.go
  pkg/channel/consolidated/status/status_test.go
  pkg/common/consumer/consumer_handler.go
  pkg/common/consumer/consumer_handler_test.go
  pkg/source/adapter/adapter.go
  third_party/VENDOR-LICENSE/knative.dev/networking/pkg/prober/LICENSE
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/golang.org/x/tools/cmd/goimports/doc.go
  vendor/golang.org/x/tools/go/ast/astutil/util.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/gocommand/version.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/knative.dev/networking/LICENSE
  vendor/knative.dev/networking/pkg/prober/doc.go
  vendor/knative.dev/networking/pkg/prober/prober.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/pod.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#451 Separate consolidated dispatcher subscription endpoint
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/dispatcher_test.go
  pkg/channel/consolidated/dispatcher/subscription_endpoint.go
  pkg/channel/consolidated/dispatcher/subscription_endpoint_test.go
Labels: approved, cla: yes, lgtm, size/L

#452 Upgraded storage version of kafkasource
  config/source/single/resources/kafkabinding.yaml
  config/source/single/resources/kafkasource.yaml
Labels: approved, cla: yes, lgtm, size/XS

#478 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#480 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/conformance/helpers/channel_addressable_resolver_cluster_role_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_channelable_manipulator_cluster_role_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_crd_metadata_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/rbac.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#483 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#484 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/conformance/helpers/sources/source_crd_rbac_test_helper.go
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#485 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/controller.go
  pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/controller.go
  pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/controller.go
  pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/controller.go
  pkg/client/injection/reconciler/sources/v1beta1/kafkasource/controller.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#464 Support arbitrary sarama metrics
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  pkg/channel/distributed/common/metrics/stats_reporter.go
  pkg/channel/distributed/common/metrics/stats_reporter_test.go
  pkg/channel/distributed/dispatcher/constants/constants.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
  pkg/channel/distributed/receiver/channel/channel.go
  pkg/channel/distributed/receiver/producer/producer.go
  pkg/channel/distributed/receiver/producer/producer_test.go
  pkg/common/metrics/README.md
  pkg/common/metrics/stats_reporter.go
  pkg/common/metrics/stats_reporter_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#492 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#493 Move metrics shutdown channels out of dispatcher config
  cmd/channel/distributed/dispatcher/main.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#489 Add "cloudevents" to the eventing-kafka config
  cmd/channel/distributed/dispatcher/main.go
  pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
  pkg/channel/consolidated/utils/util.go
  pkg/channel/distributed/common/kafka/sarama/sarama.go
  pkg/channel/distributed/common/kafka/sarama/sarama_test.go
  pkg/channel/distributed/dispatcher/constants/constants.go
  pkg/common/config/eventingkafkaconfig.go
  pkg/common/constants/constants.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M
