Repository knative-extensions/eventing-kafka, pull requests merged in 2021-01, with the labels that each got.

#288 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#286 Unifiy Sarama config building
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/utils/util.go
  pkg/channel/consolidated/utils/util_test.go
  pkg/channel/distributed/common/kafka/admin/admin_kafka.go
  pkg/channel/distributed/common/kafka/admin/admin_kafka_test.go
  pkg/channel/distributed/common/kafka/admin/admin_test.go
  pkg/channel/distributed/common/kafka/consumer/consumer_test.go
  pkg/channel/distributed/common/kafka/producer/producer_test.go
  pkg/channel/distributed/common/kafka/sarama/sarama.go
  pkg/channel/distributed/common/kafka/sarama/sarama_test.go
  pkg/channel/distributed/common/testing/util.go
  pkg/channel/distributed/controller/kafkachannel/controller.go
  pkg/channel/distributed/controller/kafkachannel/reconciler.go
  pkg/channel/distributed/controller/kafkasecret/controller.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/receiver/producer/producer.go
  pkg/common/client/config.go
  pkg/common/client/config_test.go
  pkg/common/client/kafka_scram_client.go
  pkg/common/client/sarama_test.go
  pkg/common/client/yaml.go
  pkg/common/client/yaml_test.go
  pkg/source/client.go
  pkg/source/client_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#292 Fix ko setup
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#290 Add distributed traceid
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  pkg/channel/distributed/common/config/configwatcher.go
  pkg/channel/distributed/common/config/configwatcher_test.go
  pkg/channel/distributed/controller/kafkachannel/channel.go
  pkg/channel/distributed/controller/kafkachannel/controller.go
  pkg/channel/distributed/controller/kafkachannel/dispatcher.go
  pkg/channel/distributed/controller/kafkachannel/kafkachannel.go
  pkg/channel/distributed/controller/kafkachannel/reconciler.go
  pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
  pkg/channel/distributed/controller/kafkachannel/topic.go
  pkg/channel/distributed/controller/kafkachannel/topic_test.go
  pkg/channel/distributed/controller/kafkasecret/controller.go
  pkg/channel/distributed/controller/kafkasecret/kafkachannel.go
  pkg/channel/distributed/controller/kafkasecret/receiver.go
  pkg/channel/distributed/controller/kafkasecret/reconciler.go
  pkg/channel/distributed/controller/kafkasecret/reconciler_test.go
  pkg/channel/distributed/controller/kafkasecretinjection/reconciler.go
  pkg/channel/distributed/controller/testing/mock.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#295 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#296 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#301 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_receiver.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#303 Removed namespace setup
  config/source/100-namespace.yaml
Labels: approved, cla: yes, lgtm, size/S

#304 Fix source artifact
  config/source/100-namespace.yaml
Labels: approved, cla: yes, lgtm, size/S

#306 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_receiver.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_test_helper.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#308 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/channel/config.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/factory.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#307 Removing the deprecated namespace and controller yamls
  config/source/100-deprecated-namespace.yaml
  config/source/500-deprecated-controller.yaml
Labels: approved, cla: yes, lgtm, size/M

#310 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/channel/message_dispatcher.go
  vendor/knative.dev/eventing/pkg/tracing/attributes.go
  vendor/knative.dev/eventing/pkg/tracing/names.go
  vendor/knative.dev/eventing/pkg/tracing/populate_span_transformer.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/traces.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#311 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/reconciler.go
  pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/kafkasource/reconciler.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/reconciler.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#320 Do not test controller name from generated source which can change.
  pkg/channel/distributed/controller/kafkachannel/controller_test.go
  pkg/channel/distributed/controller/kafkasecret/controller_test.go
Labels: approved, cla: yes, lgtm, size/XS

#316 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#305 Use Sarama config from config-kafka in consolidated channel
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  pkg/channel/consolidated/README.md
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
  pkg/channel/consolidated/utils/util.go
  pkg/channel/distributed/common/config/configwatcher.go
  pkg/channel/distributed/common/config/configwatcher_test.go
  pkg/channel/distributed/common/config/constants/constants.go
  pkg/channel/distributed/common/config/testing/util.go
  pkg/channel/distributed/common/kafka/sarama/sarama.go
  pkg/channel/distributed/common/kafka/sarama/sarama_test.go
  pkg/channel/distributed/common/testing/util.go
  pkg/channel/distributed/controller/kafkachannel/reconciler.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel_test.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
  pkg/channel/distributed/receiver/producer/producer.go
  pkg/channel/distributed/receiver/producer/producer_test.go
  pkg/common/client/config.go
  pkg/common/client/config_test.go
  pkg/common/constants/constants.go
  pkg/source/client.go
  pkg/source/client_test.go
Labels: approved, cla: yes, lgtm, size/L

#319 [] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/informers/bindings/v1alpha1/kafkabinding/filtered/fake/fake.go
  pkg/client/injection/informers/bindings/v1alpha1/kafkabinding/filtered/kafkabinding.go
  pkg/client/injection/informers/bindings/v1beta1/kafkabinding/filtered/fake/fake.go
  pkg/client/injection/informers/bindings/v1beta1/kafkabinding/filtered/kafkabinding.go
  pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/injection/informers/factory/filtered/filtered_factory.go
  pkg/client/injection/informers/messaging/v1alpha1/kafkachannel/filtered/fake/fake.go
  pkg/client/injection/informers/messaging/v1alpha1/kafkachannel/filtered/kafkachannel.go
  pkg/client/injection/informers/messaging/v1beta1/kafkachannel/filtered/fake/fake.go
  pkg/client/injection/informers/messaging/v1beta1/kafkachannel/filtered/kafkachannel.go
  pkg/client/injection/informers/sources/v1alpha1/kafkasource/filtered/fake/fake.go
  pkg/client/injection/informers/sources/v1alpha1/kafkasource/filtered/kafkasource.go
  pkg/client/injection/informers/sources/v1beta1/kafkasource/filtered/fake/fake.go
  pkg/client/injection/informers/sources/v1beta1/kafkasource/filtered/kafkasource.go
  pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/controller.go
  pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/controller.go
  pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/controller.go
  pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/controller.go
  pkg/client/injection/reconciler/sources/v1beta1/kafkasource/controller.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/duck/channel.go
  vendor/knative.dev/eventing/pkg/duck/listable.go
  vendor/knative.dev/eventing/pkg/duck/subscriber.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/traces.go
  vendor/knative.dev/eventing/test/lib/duck/resource_creators.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/psbinding/README.md
  vendor/knative.dev/pkg/webhook/psbinding/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#322 [Automated] Format markdown
  pkg/channel/consolidated/README.md
Labels: approved, cla: yes, lgtm, size/M

#330 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/examples/import-boss/generators/import_restrict.go
  vendor/k8s.io/gengo/examples/set-gen/generators/sets.go
  vendor/k8s.io/gengo/examples/set-gen/generators/tags.go
  vendor/k8s.io/gengo/generator/execute.go
  vendor/k8s.io/gengo/generator/import_tracker.go
  vendor/k8s.io/gengo/parser/parse.go
  vendor/knative.dev/eventing/test/README.md
  vendor/knative.dev/eventing/test/upload-test-images.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/pkg/webhook/certificates/resources/secret.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#333 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#329 fix instructions to run e2e tests locally
  test/README.md
Labels: approved, cla: yes, lgtm, size/M

#321 make space for mt source
  config/source/single/200-serviceaccount.yaml
  config/source/single/201-clusterrole.yaml
  config/source/single/202-clusterrolebinding.yaml
  config/source/single/300-kafkabinding.yaml
  config/source/single/300-kafkasource.yaml
  config/source/single/400-controller-service.yaml
  config/source/single/500-controller.yaml
  config/source/single/500-webhook-configuration.yaml
  config/source/single/README.md
  config/source/single/deployments/controller-service.yaml
  config/source/single/deployments/controller.yaml
  config/source/single/resources/kafkabinding.yaml
  config/source/single/resources/kafkasource.yaml
  config/source/single/roles/clusterrole.yaml
  config/source/single/webhooks/kafka.yaml
  hack/release.sh
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/XS

#332 #331 Add sasltype as optional secret parameter for kafka user configuration
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  config/channel/distributed/300-eventing-kafka-configmap.yaml
  config/channel/distributed/300-kafka-secret.yaml
  config/channel/distributed/README.md
  pkg/channel/distributed/common/env/constants.go
  pkg/channel/distributed/common/kafka/constants/constants.go
  pkg/channel/distributed/controller/constants/constants.go
  pkg/channel/distributed/controller/kafkachannel/controller.go
  pkg/channel/distributed/controller/kafkachannel/dispatcher.go
  pkg/channel/distributed/controller/kafkachannel/reconciler.go
  pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
  pkg/channel/distributed/controller/kafkasecret/receiver.go
  pkg/channel/distributed/controller/testing/data.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/env/environment.go
  pkg/channel/distributed/dispatcher/env/environment_test.go
  pkg/channel/distributed/receiver/env/environment.go
  pkg/channel/distributed/receiver/producer/producer.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#336 [Automated] Format markdown
  config/channel/distributed/README.md
Labels: approved, cla: yes, lgtm, size/XS

#339 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/channel/attributes/knative_error.go
  vendor/knative.dev/eventing/pkg/channel/message_dispatcher.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#340 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/conformance/helpers/metadata.go
  vendor/knative.dev/eventing/test/conformance/helpers/sources/source_crd_registry_test_helper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#345 No retry on 400 response
  pkg/channel/distributed/dispatcher/dispatcher/handler.go
  pkg/channel/distributed/dispatcher/dispatcher/handler_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S
