Repository knative-extensions/eventing-kafka, pull requests merged in 2021-02, with the labels that each got.

#349 Add steven0711dong to the owner list
  OWNERS
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#348 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#351 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/broker.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/broker.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#352 Fix #347
  pkg/channel/consolidated/dispatcher/dispatcher.go
Labels: approved, cla: yes, lgtm, size/M

#353 Fix #342
  pkg/channel/consolidated/dispatcher/dispatcher.go
Labels: approved, cla: yes, lgtm, size/XS

#362 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#361 [mt-source] Fix ce-source missing the namespace
  pkg/source/mtadapter/adapter.go
Labels: approved, cla: yes, lgtm, size/XS

#366 Increase idle connection limits from 100/2 to 1000/100
  cmd/channel/distributed/dispatcher/main.go
  pkg/channel/distributed/dispatcher/constants/constants.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#221 KafkaSource: expose dispatcher metrics and profiling data
  pkg/source/reconciler/source/resources/receive_adapter.go
Labels: approved, cla: yes, lgtm, size/XS

#364 Fix race on error channel in consumer factory
  pkg/common/consumer/consumer_factory.go
Labels: approved, cla: yes, lgtm, size/XS

#365 Propagate the auth config down to the st adapter
  config/source/multi/201-adapter-clusterrole.yaml
  pkg/source/mtadapter/adapter.go
  pkg/source/mtadapter/adapter_test.go
  test/e2e-common.sh
  test/e2e/kafka_source_reconciler_test.go
Labels: approved, cla: yes, lgtm, size/M

#344 Add http endpoint to communicate dispatcher readySubscriber status
  config/channel/consolidated/deployments/dispatcher.yaml
  pkg/channel/consolidated/dispatcher/dispatcher.go
  pkg/channel/consolidated/dispatcher/dispatcher_test.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
  pkg/common/consumer/consumer_handler.go
  pkg/common/consumer/consumer_handler_test.go
  pkg/source/adapter/adapter.go
Labels: approved, cla: yes, lgtm, size/L

#359 Adding check that requires us to just enable TLS, no need for custom certs
  pkg/channel/consolidated/utils/util.go
  pkg/common/client/config.go
Labels: approved, cla: yes, lgtm, size/M

#371 Rename mt source images mt_{controller,ra} -> mtfoo{controller,ra}
  cmd/source/mtcontroller/main.go
  cmd/source/mtreceive_adapter/main.go
  config/source/multi/deployments/adapter.yaml
  config/source/multi/deployments/controller.yaml
Labels: approved, cla: yes, lgtm, size/XS

#374 Remove @Harwayne from OWNERS.
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#372 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_types.go
  vendor/knative.dev/eventing/test/e2e/helpers/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#375 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#376 Allow v1beta1 stkafkasource topics & bootstrapservers to be mutable
  pkg/apis/sources/v1beta1/kafka_validation.go
  pkg/apis/sources/v1beta1/kafka_validation_test.go
Labels: approved, cla: yes, lgtm, size/S

#379 [0.20] Backport of 359 to 0.20
  pkg/channel/consolidated/utils/util.go
  pkg/common/client/config.go
Labels: approved, cla: yes, lgtm, size/M

#378 [0.19] Backport of 359 to 0.19
  pkg/channel/consolidated/utils/util.go
  pkg/source/client.go
Labels: approved, cla: yes, lgtm, size/M

#377 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/config.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/channel/message_receiver.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_control_plane_test_helper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#380 [mtsource] don't kill pods with placed vpods
  config/source/multi/201-adapter-clusterrole.yaml
  pkg/common/scheduler/statefulset/autoscaler.go
  pkg/common/scheduler/statefulset/snapshot.go
  pkg/common/scheduler/statefulset/snapshot_test.go
  pkg/source/adapter/adapter.go
  pkg/source/mtadapter/adapter.go
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/L

#385 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#383 slightly improve e2e doc
  test/README.md
Labels: approved, cla: yes, lgtm, size/XS

#337 Use sarama config build in source
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/common/client/admin_client.go
  pkg/source/adapter/adapter.go
  pkg/source/client/client.go
  pkg/source/client/client_test.go
  pkg/source/mtadapter/adapter.go
  pkg/source/reconciler/source/config_watcher.go
  pkg/source/reconciler/source/config_watcher_test.go
  pkg/source/reconciler/source/controller.go
  pkg/source/reconciler/source/kafkasource.go
  test/test_images/kafka-publisher/main.go
Labels: approved, cla: yes, lgtm, size/L

#391 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/reflector.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#390 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#392 Get rid of maybeAppendVar func
  pkg/source/reconciler/source/config_watcher.go
Labels: approved, cla: yes, lgtm, size/S

#394 Consolidated channel watch config kafka
  pkg/channel/consolidated/reconciler/controller/consumer_group_watcher.go
  pkg/channel/consolidated/reconciler/controller/controller.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/controller/resources/dispatcher.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
  pkg/common/constants/constants.go
Labels: approved, cla: yes, lgtm, size/M

#384 Expand number of kafkasource fields that are now mutable, add e2e tests
  pkg/apis/sources/v1beta1/kafka_validation.go
  pkg/apis/sources/v1beta1/kafka_validation_test.go
  test/e2e/kafka_source_test.go
  test/lib/creation.go
Labels: approved, cla: yes, lgtm, size/L

#396 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#397 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/config/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/config/store.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#373 Watch kafka secret update auth
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  config/channel/distributed/300-eventing-kafka-configmap.yaml
  config/channel/distributed/300-kafka-secret.yaml
  config/channel/distributed/README.md
  pkg/channel/distributed/common/config/configwatcher.go
  pkg/channel/distributed/common/config/configwatcher_test.go
  pkg/channel/distributed/common/config/secretwatcher.go
  pkg/channel/distributed/common/config/secretwatcher_test.go
  pkg/channel/distributed/common/config/testing/util.go
  pkg/channel/distributed/common/env/constants.go
  pkg/channel/distributed/common/kafka/constants/constants.go
  pkg/channel/distributed/common/kafka/sarama/sarama.go
  pkg/channel/distributed/common/kafka/sarama/sarama_test.go
  pkg/channel/distributed/common/testing/constants.go
  pkg/channel/distributed/common/testing/util.go
  pkg/channel/distributed/controller/constants/constants.go
  pkg/channel/distributed/controller/kafkachannel/controller.go
  pkg/channel/distributed/controller/kafkachannel/dispatcher.go
  pkg/channel/distributed/controller/kafkasecret/receiver.go
  pkg/channel/distributed/controller/testing/data.go
  pkg/channel/distributed/controller/util/secret.go
  pkg/channel/distributed/controller/util/secret_test.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel_test.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
  pkg/channel/distributed/dispatcher/env/environment.go
  pkg/channel/distributed/dispatcher/env/environment_test.go
  pkg/channel/distributed/dispatcher/testing/constants.go
  pkg/channel/distributed/receiver/env/environment.go
  pkg/channel/distributed/receiver/env/environment_test.go
  pkg/channel/distributed/receiver/producer/producer.go
  pkg/channel/distributed/receiver/producer/producer_test.go
  pkg/channel/distributed/receiver/testing/constants.go
  pkg/common/client/config.go
  pkg/common/client/config_test.go
  pkg/common/constants/constants.go
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#400 Updating deps
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#395 Adding HPA for webhook
  config/channel/consolidated/500-webhook-hpa.yaml
  config/channel/distributed/500-webhook-hpa.yaml
  config/channel/webhook/webhook-hpa.yaml
Labels: approved, cla: yes, lgtm, size/M

#402 [Automated] Format markdown
  config/channel/distributed/README.md
Labels: approved, cla: yes, lgtm, size/S

#403 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/config/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/config/store.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#401 [distributed] using code from eventing, that got moved there
  pkg/channel/distributed/dispatcher/dispatcher/handler.go
  pkg/channel/distributed/dispatcher/dispatcher/handler_test.go
Labels: approved, cla: yes, lgtm, size/L

#409 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#406 [mtsource] Enable stopping underlying st adapters when source is modified/removed.
  pkg/common/scheduler/statefulset/autoscaler.go
  pkg/source/mtadapter/adapter.go
  pkg/source/mtadapter/controller.go
  test/e2e-common.sh
  test/e2e/kafka_source_test.go
Labels: approved, cla: yes, lgtm, size/M

#410 Refactor distributed component mains to handle Kubernetes config better
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  pkg/channel/distributed/common/k8s/context.go
  pkg/channel/distributed/common/k8s/context_test.go
  pkg/channel/distributed/receiver/channel/channel.go
  pkg/channel/distributed/receiver/channel/channel_test.go
Labels: approved, cla: yes, lgtm, size/L

#415 update deps for 0.21
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#414 Add CODEOWNERS file for approvals
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#416 [mtsource] remove finalizer in mtadapter
  pkg/common/scheduler/statefulset/autoscaler.go
  pkg/source/mtadapter/adapter.go
  pkg/source/mtadapter/adapter_test.go
  pkg/source/mtadapter/controller.go
  pkg/source/mtadapter/kafkasource.go
Labels: approved, cla: yes, lgtm, size/M
