Repository knative-extensions/eventing-kafka, pull requests merged in 2021-07, with the labels that each got.

#750 ResetOffset RBAC Config
  config/command/resetoffset/README.md
  config/command/resetoffset/resetoffset-clusterrole.yaml
  config/command/resetoffset/resetoffset-crd.yaml
Labels: approved, cla: yes, lgtm, size/M

#748 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/warning_handler.go
  vendor/knative.dev/pkg/ptr/value.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#751 Missing webhook rbac
  config/channel/webhook/webhook-clusterrole.yaml
Labels: approved, bug, cla: yes, lgtm, size/XS

#752 Missing webhook rbac (backport)
  config/channel/webhook/webhook-clusterrole.yaml
Labels: approved, bug, cla: yes, lgtm, size/XS

#747 [main] Update actions
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
Labels: approved, cla: yes, lgtm, size/XS

#753 Initial ResetOffset Webhook
  cmd/webhook/main.go
  config/channel/webhook/README.md
  config/channel/webhook/webhook-clusterrole.yaml
  config/channel/webhook/webhook-deployment-ro.yaml
  pkg/channel/webhook/controller.go
  pkg/channel/webhook/controller_test.go
Labels: approved, cla: yes, lgtm, size/L

#754 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/broker.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/trigger.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/reconciler-test/cmd/eventshub/main.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_log.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/eventshub.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/eventshub_image.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#756 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/receiver/receiver.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#755 Change kafkachannel status when paused
  cmd/channel/distributed/dispatcher/main.go
  pkg/channel/distributed/dispatcher/constants/constants.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel.go
  pkg/channel/distributed/dispatcher/controller/kafkachannel_test.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher.go
  pkg/channel/distributed/dispatcher/dispatcher/dispatcher_test.go
  pkg/channel/distributed/dispatcher/testing/factory.go
  pkg/channel/distributed/dispatcher/testing/kafkachannel.go
  pkg/common/consumer/consumer_manager.go
  pkg/common/consumer/consumer_manager_test.go
  pkg/common/consumer/managed_group.go
  pkg/common/consumer/managed_group_test.go
  pkg/common/consumer/testing/mocks.go
Labels: approved, cla: yes, lgtm, size/XL

#758 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#739 [Source] Optimize InitOffsets
  pkg/common/kafka/sarama/batch_get_offsets.go
  pkg/common/kafka/sarama/batch_get_offsets_test.go
  pkg/source/client/offsets.go
Labels: approved, cla: yes, lgtm, size/L

#761 Enable ResetOffset in Distributed KafkaChannel
  cmd/channel/distributed/controller/main.go
  config/channel/distributed/100-resetoffset-clusterrole.yaml
  config/channel/distributed/200-controller-clusterrolebinding.yaml
  config/channel/distributed/300-resetoffset-crd.yaml
  config/channel/distributed/500-webhook-deployment.yaml
  pkg/channel/distributed/README.md
  pkg/common/kafka/sarama/sarama_test.go
Labels: approved, cla: yes, lgtm, size/M

#759 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/gobuffalo/flect/plural_rules.go
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/buffered_write_syncer.go
  vendor/go.uber.org/zap/zapcore/clock.go
  vendor/go.uber.org/zap/zapcore/entry.go
  vendor/golang.org/x/oauth2/google/doc.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/aws.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/clientauth.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/impersonate.go
  vendor/golang.org/x/oauth2/google/jwt.go
  vendor/golang.org/x/tools/go/ast/astutil/rewrite.go
  vendor/golang.org/x/tools/internal/gocommand/version.go
  vendor/golang.org/x/tools/internal/typeparams/doc.go
  vendor/golang.org/x/tools/internal/typeparams/notypeparams.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/eventing/pkg/channel/metrics.go
  vendor/knative.dev/eventing/pkg/channel/stats_reporter.go
  vendor/knative.dev/eventing/pkg/metrics/metrics.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#763 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/controller.go
  pkg/client/injection/reconciler/kafka/v1alpha1/resetoffset/controller.go
  pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/controller.go
  pkg/client/injection/reconciler/sources/v1beta1/kafkasource/controller.go
  third_party/VENDOR-LICENSE/github.com/cloudevents/sdk-go/observability/opencensus/v2/LICENSE
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/pkg/metrics/metrics.go
  vendor/knative.dev/eventing/pkg/metrics/source/stats_reporter.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/sender/sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#764 use source.StatsReporter from knative.dev/eventing
  pkg/source/adapter/adapter.go
  pkg/source/adapter/adapter_benchmark_test.go
  pkg/source/mtadapter/adapter.go
  pkg/source/mtadapter/adapter_test.go
Labels: approved, cla: yes, lgtm, size/S

#765 missed an import when switching over to eventing's source.StatsReporter
  pkg/source/adapter/adapter_test.go
Labels: approved, cla: yes, lgtm, size/XS

#766 add missing condition types
  pkg/apis/sources/v1beta1/kafka_lifecycle_mt.go
  pkg/apis/sources/v1beta1/mttest/kafka_lifecycle_mt_test.go
Labels: approved, cla: yes, lgtm, size/XS

#771 Correct ResetOffset README
  config/command/resetoffset/README.md
Labels: approved, cla: yes, lgtm, size/XS

#772 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#773 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/request.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#775 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#777 Update README.md
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#778 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#782 [distributed KafkaChannel] Kafka AdminClient Error Handling
  pkg/channel/distributed/controller/kafkachannel/reconciler.go
  pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
Labels: approved, cla: yes, lgtm, size/L

#780 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#783 [distributed KafkaChannel] Add receiver/dispatcher labels to Pods as well as Deployments
  pkg/channel/distributed/controller/kafkachannel/dispatcher.go
  pkg/channel/distributed/controller/kafkachannel/receiver.go
  pkg/channel/distributed/controller/testing/data.go
Labels: approved, cla: yes, lgtm, size/M

#776 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS
