Repository knative-extensions/eventing-kafka, pull requests merged in 2022-01, with the labels that each got.

#1038 Validate SourceSpec in KafkaSource
  pkg/apis/sources/v1beta1/kafka_validation.go
  test/e2e/helpers/kafka_source.go
Labels: size/XS, lgtm, approved

#1040 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1042 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1044 Consumer manager use factory merged errors
  pkg/common/consumer/consumer_factory.go
  pkg/common/consumer/consumer_manager.go
  pkg/common/consumer/consumer_manager_test.go
  pkg/common/consumer/managed_group.go
  pkg/common/consumer/managed_group_test.go
Labels: lgtm, approved, size/L

#1024 Differentiate KafkaChannel Status ConditionSets
  cmd/channel/consolidated/README.md
  cmd/channel/consolidated/controller/main.go
  cmd/channel/consolidated/dispatcher/main.go
  cmd/channel/distributed/controller/main.go
  cmd/channel/distributed/dispatcher/main.go
  cmd/channel/distributed/receiver/main.go
  pkg/apis/messaging/v1beta1/kafka_channel_lifecycle.go
  pkg/apis/messaging/v1beta1/kafka_channel_lifecycle_test.go
  pkg/channel/consolidated/apis/messaging/kafka_channel_lifecycle.go
  pkg/channel/consolidated/apis/messaging/kafka_channel_lifecycle_test.go
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
  pkg/channel/consolidated/reconciler/testing/kafkachannel.go
  pkg/channel/distributed/apis/messaging/kafka_channel_lifecycle.go
  pkg/channel/distributed/apis/messaging/kafka_channel_lifecycle_test.go
  pkg/channel/distributed/controller/kafkachannel/dispatcher.go
  pkg/channel/distributed/controller/kafkachannel/kafkachannel.go
  pkg/channel/distributed/controller/kafkachannel/receiver.go
  pkg/channel/distributed/controller/kafkachannel/reconciler_test.go
  pkg/channel/distributed/controller/testing/data.go
  pkg/channel/distributed/dispatcher/testing/kafkachannel.go
  pkg/channel/distributed/receiver/channel/channel.go
  pkg/channel/distributed/receiver/testing/channel.go
Labels: size/XXL, lgtm, approved

#1051 Fix KafkaSource validation error for missing bootstrapServers
  pkg/apis/sources/v1beta1/kafka_validation.go
Labels: size/XS, lgtm, approved

#1049 Attempting to un-flaky the tests that use the zap test logger
  pkg/common/consumer/consumer_manager_test.go
  pkg/common/consumer/managed_group_test.go
Labels: lgtm, approved, size/M

#1045 [release-1.1] Consumer manager use factory merged errors (#1044)
  pkg/common/consumer/consumer_factory.go
  pkg/common/consumer/consumer_manager.go
  pkg/common/consumer/consumer_manager_test.go
  pkg/common/consumer/managed_group.go
  pkg/common/consumer/managed_group_test.go
Labels: lgtm, approved, size/L

#1048 [release-1.0] Consumer manager use factory merged errors (#1044)
  go.mod
  go.sum
  pkg/common/consumer/consumer_factory.go
  pkg/common/consumer/consumer_manager.go
  pkg/common/consumer/consumer_manager_test.go
  pkg/common/consumer/managed_group.go
  pkg/common/consumer/managed_group_test.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1047 [release-0.26] Consumer manager use factory merged errors (#1044)
  pkg/apis/bindings/v1beta1/zz_generated.deepcopy.go
  pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kafka/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/messaging/v1beta1/zz_generated.deepcopy.go
  pkg/apis/sources/v1beta1/zz_generated.deepcopy.go
  pkg/common/consumer/consumer_factory.go
  pkg/common/consumer/consumer_manager.go
  pkg/common/consumer/consumer_manager_test.go
  pkg/common/consumer/managed_group.go
  pkg/common/consumer/managed_group_test.go
Labels: lgtm, approved, size/L

#1052 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1053 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/go-logr/logr/.golangci.yaml
  vendor/github.com/go-logr/logr/CHANGELOG.md
  vendor/github.com/go-logr/logr/CONTRIBUTING.md
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klog_file_others.go
  vendor/k8s.io/klog/v2/klog_file_windows.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/main.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#1054 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved

#1057 Define status.deadLetterSinkUri in KafkaChannel CRD
  config/channel/resources/kafkachannel-crd.yaml
Labels: size/XS, lgtm, approved

#1058 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/doc.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/feature/level.go
  vendor/knative.dev/reconciler-test/pkg/feature/states.go
  vendor/knative.dev/reconciler-test/pkg/feature/timing.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/knative.dev/reconciler-test/pkg/state/kvstore.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1059 [main] Update actions
  .github/workflows/knative-security.yaml
Labels: size/XS, lgtm, approved

#1060 fix vulnerabilities
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/user_info.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1061 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-tests.sh
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/eventing/test/lib/operation.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1062 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/test/e2e-rekt-tests.sh
  vendor/knative.dev/eventing/test/upgrade/prober/sender.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/config/logger.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter_log.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1063 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1065 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/upgrade/prober/configuration.go
  vendor/knative.dev/eventing/test/upgrade/prober/prober.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1066 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#1067 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1068 Custom leader-election configuration for KafkaChannel
  config/channel/config/leader-election-configmap.yaml
  config/channel/consolidated/400-leaderelection-configmap.yaml
  config/channel/consolidated/deployments/controller.yaml
  config/channel/distributed/300-leaderelection-configmap.yaml
  config/channel/distributed/500-controller-deployment.yaml
  config/channel/webhook/webhook-deployment-ro.yaml
  config/channel/webhook/webhook-deployment.yaml
Labels: lgtm, approved, size/M

#1071 [main] Update actions
  .github/workflows/knative-security.yaml
Labels: size/XS, lgtm, approved

#1072 Check if ps is not installed and install it
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved

#1070 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1075 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1076 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/inmemorychannel.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/shell/project.go
  vendor/knative.dev/pkg/apiextensions/storageversion/migrator.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: lgtm, approved, size/M
