Repository knative-extensions/eventing-kafka, pull requests merged in 2022-04, with the labels that each got.

#1146 Activating HA scheduler for scaling and scheduling KafkaSource consumers
  config/source/common/configmaps/config-descheduler.yaml
  config/source/common/configmaps/config-scheduler.yaml
  config/source/multi/deployments/controller.yaml
  pkg/source/reconciler/mtsource/controller.go
Labels: lgtm, approved, size/L

#1143 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/S

#1147 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1144 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, size/XL

#1148 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1149 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1132 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/exit.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/knative.dev/eventing/pkg/reconciler/sugar/filters.go
  vendor/knative.dev/eventing/pkg/reconciler/sugar/labels.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/trigger.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e/helpers/broker_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/sugar_helper.go
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/test_images/utils.go
  vendor/knative.dev/eventing/test/upgrade/prober/config.toml
  vendor/knative.dev/eventing/test/upgrade/prober/configuration.go
  vendor/knative.dev/eventing/test/upgrade/prober/forwarder.go
  vendor/knative.dev/eventing/test/upgrade/prober/receiver.go
  vendor/knative.dev/eventing/test/upgrade/prober/sender.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/client/receiver.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/config/defaults.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/config/structure.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/config/tracing.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/event/services.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/event/tracing.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/forwarder/services.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/receiver/services.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/sender/operations.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/sender/services.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/sender/types.go
  vendor/knative.dev/hack/CODE-OF-CONDUCT.md
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/reconciler-test/pkg/feature/steps.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#1150 [main] Update actions
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, size/S

#1151 Enable collecting traces in upgrade tests
  test/config/monitoring.yaml
  test/test_images/wathola-kafka-sender/main.go
  test/upgrade/continual/channel-config.toml
  test/upgrade/continual/kafkasender.go
  test/upgrade/continual/source-config.toml
  test/upgrade/installation/eventing_core.go
  test/upgrade/test_main.go
Labels: lgtm, approved, size/M

#1152 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/adapter/v2/configurator_configmap.go
  vendor/knative.dev/eventing/pkg/adapter/v2/configurator_environment.go
  vendor/knative.dev/eventing/pkg/adapter/v2/context.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/adapter/v2/util/crstatusevent/eventsstatus.go
  vendor/knative.dev/eventing/pkg/scheduler/statefulset/scheduler.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#1153 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1139 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: lgtm, approved, size/M

#1156 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/scheduler/scheduler.go
  vendor/knative.dev/eventing/pkg/scheduler/state/state.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1160 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1154 [release-1.2] Backport upgrade tracing
  pkg/channel/consolidated/dispatcher/consumer_message_handler.go
  pkg/channel/distributed/dispatcher/dispatcher/handler.go
  pkg/common/tracing/tracing.go
  pkg/common/tracing/tracing_test.go
  pkg/source/adapter/adapter.go
Labels: lgtm, approved, size/S

#1158 Generate consumer group in KafkaSourceUpdate test
  test/e2e/helpers/kafka_source_test_helper.go
Labels: size/XS, lgtm, approved

#1157 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: lgtm, approved, size/M
