Repository knative-extensions/eventing-kafka, pull requests merged in 2022-02, with the labels that each got.

#1077 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1078 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/test/upgrade/functions.go
  vendor/knative.dev/pkg/test/upgrade/logger.go
  vendor/knative.dev/pkg/test/upgrade/private_types.go
  vendor/knative.dev/pkg/test/upgrade/steps.go
  vendor/knative.dev/pkg/test/upgrade/suite_execution.go
  vendor/knative.dev/pkg/test/upgrade/types.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/user_info.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/receiver/receiver.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/k8s/job.go
  vendor/knative.dev/reconciler-test/pkg/k8s/pod.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#1079 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: lgtm, approved, size/M

#1081 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1082 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/feature/logging.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1083 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1084 Use default logger configuration
  test/upgrade/upgrade_test.go
Labels: lgtm, approved, size/S

#1086 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1088 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/placement_types.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1092 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/reconciler-test/pkg/environment/logging.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1096 Do not skip the status test
  test/conformance/channel_status_test.go
Labels: size/XS, lgtm, approved

#1093 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, lgtm, approved

#1099 Revert "Update constants.go (#1085)"
  pkg/common/constants/constants.go
Labels: size/XS, lgtm, approved

#1098 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/scheduler/statefulset/scheduler.go
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/url.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1100 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, lgtm, approved

#1102 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1104 Prevent excessive wait time in KafkaSender for upgrade tests
  test/upgrade/continual/kafkasender.go
Labels: size/XS, lgtm, approved

#1101 Set resource limit for single-tenant Kafka source
  pkg/source/reconciler/source/resources/receive_adapter.go
Labels: lgtm, approved, size/S

#1110 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/test/upgrade/prober/sender.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1106 KafkaSource continues Trace from messages
  pkg/channel/consolidated/dispatcher/consumer_message_handler.go
  pkg/channel/distributed/dispatcher/dispatcher/handler.go
  pkg/common/tracing/tracing.go
  pkg/common/tracing/tracing_test.go
  pkg/source/adapter/adapter.go
Labels: lgtm, approved, size/S

#1111 [consolidated] Retry on reconcile subscriber error
  pkg/channel/consolidated/reconciler/controller/kafkachannel.go
Labels: size/XS, lgtm, approved
