Repository knative-extensions/eventing-kafka, pull requests merged in 2022-05, with the labels that each got.

#1163 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1145 Add KO_FLAGS to e2e test
  test/e2e-common.sh
Labels: lgtm, approved, size/S, ok-to-test

#1166 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1167 The channelTemplateSpec: is deprecated and replaced by channel-template-spec
  test/upgrade/continual/channel.go
Labels: size/XS, lgtm, approved

#1172 Correctly handle KafkaChannels with long names
  pkg/channel/consolidated/reconciler/controller/resources/service.go
  pkg/channel/consolidated/reconciler/controller/resources/service_test.go
Labels: lgtm, approved, size/M

#1177 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1171 Update to strimzi 0.28 and kafka 3.1
  test/config/100-kafka-ephemeral-triple-3.1.0.yaml
  test/config/100-strimzi-cluster-operator-0.28.0.yaml
  test/e2e-common.sh
Labels: lgtm, approved, size/L, ok-to-test

#1178 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1165 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/event/services.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/event/types.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/sender/services.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1180 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1179 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/resources/eventing.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1181 Remove calling 'ExecuteLocalYAML', b/c it is deprecated
  test/rekt/resources/kafkacat/kafkacat_test.go
  test/rekt/resources/kafkasource/kafkasource_test.go
  test/rekt/resources/kafkatopic/topic_test.go
Labels: size/XS, lgtm, approved

#1182 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/knative.dev/eventing/test/upgrade/prober/prober.go
  vendor/knative.dev/eventing/test/upgrade/prober/sender.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/knative.dev/reconciler-test/pkg/manifest/templates.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1176 Add KO_FLAGS to upload_test_images()
  test/upload-test-images.sh
Labels: size/XS, lgtm, approved, ok-to-test

#1185 Adding a lib for creating a simple KafkaUser for a given topic
  test/e2e/helpers/kafka_helper.go
Labels: lgtm, approved, size/M

#1186 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1187 Adding authType argument
  test/e2e/helpers/kafka_helper.go
Labels: size/XS, lgtm, approved

#1189 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/source/config_watcher.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1191 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1190 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#1192 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S
