Repository knative-extensions/eventing-kafka, pull requests merged in 2022-10, with the labels that each got.

#1251 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#1250 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1246 [release-v1.5] Upgrade dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/test/test_client.go
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_message_handler.go
  vendor/knative.dev/eventing/pkg/channel/message_receiver.go
  vendor/knative.dev/eventing/pkg/scheduler/plugins/core/availabilitynodepriority/availability_node_priority.go
  vendor/knative.dev/eventing/pkg/scheduler/plugins/core/availabilityzonepriority/availability_zone_priority.go
  vendor/knative.dev/eventing/pkg/scheduler/scheduler.go
  vendor/knative.dev/eventing/pkg/scheduler/statefulset/scheduler.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/traces.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/zipkin.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing_test_helper.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1254 update deps
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1255 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#1256 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1258 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/pelletier/go-toml/v2/LICENSE
  vendor/github.com/pelletier/go-toml/v2/.gitattributes
  vendor/github.com/pelletier/go-toml/v2/.gitignore
  vendor/github.com/pelletier/go-toml/v2/.golangci.toml
  vendor/github.com/pelletier/go-toml/v2/.goreleaser.yaml
  vendor/github.com/pelletier/go-toml/v2/CONTRIBUTING.md
  vendor/github.com/pelletier/go-toml/v2/Dockerfile
  vendor/github.com/pelletier/go-toml/v2/LICENSE
  vendor/github.com/pelletier/go-toml/v2/README.md
  vendor/github.com/pelletier/go-toml/v2/SECURITY.md
  vendor/github.com/pelletier/go-toml/v2/ci.sh
  vendor/github.com/pelletier/go-toml/v2/decode.go
  vendor/github.com/pelletier/go-toml/v2/errors.go
  vendor/github.com/pelletier/go-toml/v2/internal/ast/ast.go
  vendor/github.com/pelletier/go-toml/v2/internal/ast/builder.go
  vendor/github.com/pelletier/go-toml/v2/internal/ast/kind.go
  vendor/github.com/pelletier/go-toml/v2/internal/danger/danger.go
  vendor/github.com/pelletier/go-toml/v2/internal/danger/typeid.go
  vendor/github.com/pelletier/go-toml/v2/internal/tracker/key.go
  vendor/github.com/pelletier/go-toml/v2/internal/tracker/seen.go
  vendor/github.com/pelletier/go-toml/v2/localtime.go
  vendor/github.com/pelletier/go-toml/v2/marshaler.go
  vendor/github.com/pelletier/go-toml/v2/parser.go
  vendor/github.com/pelletier/go-toml/v2/scanner.go
  vendor/github.com/pelletier/go-toml/v2/strict.go
  vendor/github.com/pelletier/go-toml/v2/targets.go
  vendor/github.com/pelletier/go-toml/v2/types.go
  vendor/github.com/pelletier/go-toml/v2/unmarshaler.go
  vendor/github.com/pelletier/go-toml/v2/utf8.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/config/reader.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved
