Repository knative-extensions/eventing-kafka, pull requests merged in 2022-08, with the labels that each got.

#1221 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/internal/clock/README.md
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/dbg/dbg.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#1222 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/cmd/eventshub/main.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/sender/sender.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/utils.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter_tracing.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1224 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1225 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1226 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1227 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, skip-review

#1229 Skip channel chain test
  test/e2e/channel_chain_test.go
Labels: size/XS, lgtm, approved

#1228 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#1231 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1230 [main] Upgrade to latest dependencies
  .codecov.yaml
  go.mod
  go.sum
  pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
  pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
  pkg/channel/distributed/common/config/tracing.go
  pkg/channel/distributed/common/config/tracing_test.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_receiver.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracing/setup.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/sender/sender.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1234 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1233 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/config.go
  vendor/knative.dev/eventing/pkg/adapter/v2/configurator_configmap.go
  vendor/knative.dev/eventing/pkg/adapter/v2/configurator_environment.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/test/test_images/event-sender/main.go
  vendor/knative.dev/eventing/test/test_images/recordevents/main.go
  vendor/knative.dev/eventing/test/test_images/utils.go
  vendor/knative.dev/eventing/test/test_images/wathola-forwarder/main.go
  vendor/knative.dev/eventing/test/test_images/wathola-receiver/main.go
  vendor/knative.dev/eventing/test/test_images/wathola-sender/main.go
  vendor/knative.dev/eventing/test/upgrade/prober/configuration.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/config/tracing.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/forwarder/services.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/receiver/services.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/sender/operations.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/sender/services.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/sender/types.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1235 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1236 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S
