Repository knative-extensions/eventing-kafka, pull requests merged in 2023-08, with the labels that each got.

#1365 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1366 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, skip-review

#1367 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1370 Remove usage of deprecated kncloudevents.CloudEventsRequest
  pkg/source/adapter/adapter.go
  pkg/source/adapter/adapter_test.go
  pkg/source/adapter/message.go
Labels: lgtm, approved, size/M

#1369 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e-rekt-tests.sh
  vendor/knative.dev/eventing/test/e2e-upgrade-tests.sh
  vendor/knative.dev/eventing/test/upgrade/prober/configuration.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1372 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1375 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1374 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/gobuffalo/flect/README.md
  vendor/github.com/gobuffalo/flect/SHOULDERS.md
  vendor/github.com/gobuffalo/flect/camelize.go
  vendor/github.com/gobuffalo/flect/custom_data.go
  vendor/github.com/gobuffalo/flect/humanize.go
  vendor/github.com/gobuffalo/flect/pascalize.go
  vendor/github.com/gobuffalo/flect/plural_rules.go
  vendor/github.com/gobuffalo/flect/pluralize.go
  vendor/github.com/gobuffalo/flect/rule.go
  vendor/github.com/gobuffalo/flect/singular_rules.go
  vendor/github.com/gobuffalo/flect/singularize.go
  vendor/github.com/gobuffalo/flect/titleize.go
  vendor/github.com/gobuffalo/flect/underscore.go
  vendor/github.com/gobuffalo/flect/version.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/mremap.go
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/syscall_linux_loong64.go
  vendor/golang.org/x/sys/unix/syscall_linux_mips64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_netbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/forwarder/forwarder.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#1380 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e_flags.go
  vendor/modules.txt
Labels: lgtm, approved, size/S
