Repository knative-extensions/eventing-kafka, pull requests merged in 2023-02, with the labels that each got.

#1290 Remove deprecated test
  test/e2e/channel_chain_test.go
  test/e2e/channel_dls_test.go
Labels: lgtm, approved, size/M

#1291 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/scheduler/statefulset/scheduler.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1292 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1294 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/duck/listable.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/eventing/pkg/scheduler/scheduler.go
  vendor/knative.dev/eventing/pkg/scheduler/state/state.go
  vendor/knative.dev/eventing/pkg/scheduler/statefulset/scheduler.go
  vendor/knative.dev/eventing/pkg/utils/secret.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_event_transformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_chain_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_dls_test_helper.go
  vendor/knative.dev/hack/shell/executor.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/reconciler-test/pkg/k8s/job.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1293 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/M, skip-review

#1295 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/resources/service/options.go
  vendor/knative.dev/reconciler-test/pkg/resources/service/service.go
  vendor/knative.dev/reconciler-test/pkg/resources/service/service.yaml
  vendor/knative.dev/reconciler-test/resources/svc/service.go
  vendor/knative.dev/reconciler-test/resources/svc/service.yaml
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1298 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/manifest/options.go
  vendor/knative.dev/reconciler-test/pkg/resources/service/options.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1301 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1300 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/environment/flags.go
  vendor/knative.dev/reconciler-test/pkg/environment/images.go
  vendor/knative.dev/reconciler-test/pkg/environment/standard.go
  vendor/knative.dev/reconciler-test/pkg/images/file/file.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1303 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/reconciler.go
  pkg/client/injection/reconciler/kafka/v1alpha1/resetoffset/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/kafkasource/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/reconciler-test/pkg/environment/istio.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/environment/standard.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/manifest/options.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1304 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1305 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/controller.go
  pkg/client/injection/reconciler/kafka/v1alpha1/resetoffset/controller.go
  pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/controller.go
  pkg/client/injection/reconciler/sources/v1beta1/kafkasource/controller.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1302 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, skip-review
