Repository knative-extensions/eventing-kafka, pull requests merged in 2023-01, with the labels that each got.

#1279 [1.5] Use PodDisruptionBudget v1
  config/channel/webhook/webhook-hpa.yaml
Labels: size/XS, lgtm, approved

#1283 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1286 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1287 Update API versions of HorizontalPodAutoscaler and PodDisruptionBudget
  config/channel/webhook/webhook-hpa.yaml
Labels: size/XS, lgtm, approved

#1289 fixes tests
  go.mod
  go.sum
  test/rekt/features/kafkachannel/util.go
  test/upgrade/upgrade_test.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/parser/expression_visitor.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/utils/casting.go
  vendor/github.com/cloudevents/sdk-go/v2/alias.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/abuse_protection.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/deployment.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/apiserversouce.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_helper.go
  vendor/knative.dev/eventing/test/lib/logexporter.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/test/logstream/v2/interface.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/knative.dev/pkg/test/upgrade/functions.go
  vendor/knative.dev/pkg/test/upgrade/logger.go
  vendor/knative.dev/pkg/test/upgrade/private_types.go
  vendor/knative.dev/pkg/test/upgrade/steps.go
  vendor/knative.dev/pkg/test/upgrade/suite_execution.go
  vendor/knative.dev/pkg/test/upgrade/types.go
  vendor/knative.dev/reconciler-test/pkg/environment/execution.go
  vendor/knative.dev/reconciler-test/pkg/environment/logging.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/rbac.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/sender/sender.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#1284 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, approved, skip-review
