Repository knative-extensions/eventing-kafka, pull requests merged in 2023-06, with the labels that each got.

#1345 Update dependencies and fix compile issues
  go.mod
  go.sum
  pkg/source/adapter/adapter.go
  pkg/source/adapter/adapter_benchmark_test.go
  pkg/source/adapter/adapter_test.go
  pkg/source/mtadapter/adapter.go
  pkg/source/mtadapter/adapter_test.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/eventingtls/eventingtls.go
  vendor/knative.dev/eventing/pkg/eventingtls/servermanager.go
  vendor/knative.dev/eventing/pkg/kncloudevents/http_client.go
  vendor/knative.dev/eventing/pkg/kncloudevents/http_client_new.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender_new.go
  vendor/knative.dev/eventing/pkg/kncloudevents/utils.go
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/104-forwarder.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/forwarder/forwarder.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/100-sa.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/101-rbac.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/rbac.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#1346 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1344 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/test_helper.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_lifecycle.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1348 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1349 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/cmd/heartbeats/main.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_lifecycle.go
  vendor/knative.dev/eventing/pkg/eventingtls/eventingtls.go
  vendor/knative.dev/eventing/test/test_images/wathola-fetcher/main.go
  vendor/knative.dev/eventing/test/upgrade/prober/forwarder.go
  vendor/knative.dev/eventing/test/upgrade/prober/receiver.go
  vendor/knative.dev/eventing/test/upgrade/prober/sender.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/options.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/options.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/options.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/event_info_matchers.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/step.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#1351 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1352 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_defaults.go
  vendor/knative.dev/eventing/pkg/kncloudevents/http_client_new.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1353 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_defaults.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1354 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1355 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/modules.txt
Labels: lgtm, approved, size/S
