Repository knative-extensions/eventing-kafka, pull requests merged in 2024-01, with the labels that each got.

#1449 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1451 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1452 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/kafkasource/reconciler.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/google.golang.org/api/iamcredentials/v1/iamcredentials-gen.go
  vendor/google.golang.org/api/internal/settings.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/option/internaloption/internaloption.go
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/api/transport/grpc/dial.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/configmap/informer/synced_callback.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/hash/hash.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/105-certificate-service.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/utils.go
  vendor/knative.dev/reconciler-test/pkg/resources/secret/secret.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1454 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/doc.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1455 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1457 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1459 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1461 Update Golang in go.mod to 1.21
  go.mod
  go.sum
Labels: lgtm, approved, size/S

#1463 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1465 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/internal/.repo-metadata-full.json
  vendor/cloud.google.com/go/internal/trace/trace.go
  vendor/cloud.google.com/go/storage/CHANGES.md
  vendor/cloud.google.com/go/storage/grpc_client.go
  vendor/cloud.google.com/go/storage/http_client.go
  vendor/cloud.google.com/go/storage/internal/apiv2/auxiliary.go
  vendor/cloud.google.com/go/storage/internal/apiv2/doc.go
  vendor/cloud.google.com/go/storage/internal/apiv2/storage_client.go
  vendor/cloud.google.com/go/storage/internal/version.go
  vendor/cloud.google.com/go/storage/invoke.go
  vendor/cloud.google.com/go/storage/storage.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/alts/internal/handshaker/handshaker.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/unix/unix.go
  vendor/google.golang.org/grpc/internal/tcp_keepalive_others.go
  vendor/google.golang.org/grpc/internal/tcp_keepalive_windows.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#1466 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/register.go
  vendor/knative.dev/eventing/pkg/auth/serviceaccount.go
  vendor/modules.txt
Labels: lgtm, approved, size/M
